# Generated by Django 4.2.29 on 2026-07-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditlog', '0002_searchanalyticsevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='searchanalyticsevent',
            new_name='auditlog_se_event_t_581c95_idx',
            old_name='auditlog_se_event_t_3b4c83_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalyticsevent',
            new_name='auditlog_se_query_bce25e_idx',
            old_name='auditlog_se_query_a0b9f8_idx',
        ),
        migrations.RenameIndex(
            model_name='searchanalyticsevent',
            new_name='auditlog_se_search__436532_idx',
            old_name='auditlog_se_search_2e0bf7_idx',
        ),
    ]
