# Generated by Django 4.2.29 on 2026-07-28 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
        ('partner', '0006_auto_20200724_0909'),
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('marketplace', '0005_supplier_offers_requests_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayableLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('supplier_unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payable_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payable', 'Payable'), ('on_hold', 'On Hold'), ('approved', 'Approved'), ('paid', 'Paid'), ('disputed', 'Disputed'), ('reversed', 'Reversed')], default='pending', max_length=32)),
                ('source_status', models.CharField(blank=True, max_length=64)),
                ('payout_reference', models.CharField(blank=True, max_length=128)),
                ('reversal_reason', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payable_ledger', to='marketplace.supplierorderlineallocation')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payable_ledgers', to='order.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payable_ledgers', to='order.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payable_ledgers', to='partner.partner')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payable_ledgers', to='catalogue.product')),
                ('stockrecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payable_ledgers', to='partner.stockrecord')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_ledgers', to='marketplace.supplierprofile')),
                ('supplier_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_ledgers', to='marketplace.supplierproductoffer')),
            ],
            options={
                'ordering': ['order_id', 'line_id', 'id'],
                'indexes': [models.Index(fields=['partner', 'status'], name='supp_pay_partner_status'), models.Index(fields=['supplier', 'status'], name='supp_pay_supplier_status'), models.Index(fields=['order', 'status'], name='supp_pay_order_status'), models.Index(fields=['status', 'updated_at'], name='supp_pay_status_updated')],
            },
        ),
    ]
