# Generated by Django 4.2.29 on 2026-07-28 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0006_auto_20200724_0909'),
        ('marketplace', '0006_supplierpayableledger'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayoutBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_reference', models.CharField(max_length=64, unique=True)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=32)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry_count', models.PositiveIntegerField(default=0)),
                ('payout_method', models.CharField(blank=True, max_length=64)),
                ('payout_reference', models.CharField(blank=True, max_length=128)),
                ('evidence_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payout_batches', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payout_batches', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_supplier_payout_batches', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_payout_batches', to='partner.partner')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_batches', to='marketplace.supplierprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPayoutBatchEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='marketplace.supplierpayoutbatch')),
                ('payable', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout_batch_entry', to='marketplace.supplierpayableledger')),
            ],
            options={
                'ordering': ['batch_id', 'id'],
                'indexes': [models.Index(fields=['batch', 'currency'], name='supp_payout_entry_batch')],
            },
        ),
        migrations.AddIndex(
            model_name='supplierpayoutbatch',
            index=models.Index(fields=['status', '-created_at'], name='supp_payout_status_created'),
        ),
        migrations.AddIndex(
            model_name='supplierpayoutbatch',
            index=models.Index(fields=['supplier', 'status'], name='supp_payout_supplier_status'),
        ),
        migrations.AddIndex(
            model_name='supplierpayoutbatch',
            index=models.Index(fields=['batch_reference'], name='supp_payout_reference'),
        ),
    ]
