# Generated by Django 4.2.29 on 2026-07-28 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_alter_line_num_allocated'),
        ('marketplace', '0007_supplierpayoutbatch_supplierpayoutbatchentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierPayableAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_reference', models.CharField(max_length=64, unique=True)),
                ('adjustment_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit'), ('reversal', 'Reversal')], default='debit', max_length=32)),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('approved', 'Approved'), ('applied', 'Applied'), ('void', 'Void')], default='pending_review', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source_reference', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_supplier_payable_adjustments', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_supplier_payable_adjustments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_supplier_payable_adjustments', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payable_adjustments', to='order.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payable_adjustments', to='order.order')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_payable_adjustments', to='partner.partner')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='marketplace.supplierpayableledger')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payable_adjustments', to='marketplace.supplierprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['supplier', 'status'], name='supp_adj_supplier_status'), models.Index(fields=['partner', 'status'], name='supp_adj_partner_status'), models.Index(fields=['order', 'status'], name='supp_adj_order_status'), models.Index(fields=['adjustment_reference'], name='supp_adj_reference')],
            },
        ),
    ]
