# Generated by Django 4.2.29 on 2026-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_supplierpayableadjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayableadjustment',
            name='erpnext_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supplierpayableadjustment',
            name='erpnext_sync_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierpayableadjustment',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierpayableadjustment',
            name='erpnext_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayableledger',
            name='erpnext_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supplierpayableledger',
            name='erpnext_sync_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierpayableledger',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierpayableledger',
            name='erpnext_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierpayoutbatch',
            name='erpnext_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='supplierpayoutbatch',
            name='erpnext_sync_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supplierpayoutbatch',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='supplierpayoutbatch',
            name='erpnext_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='supplierpayableledger',
            index=models.Index(fields=['erpnext_sync_status', 'updated_at'], name='supp_pay_erp_status'),
        ),
        migrations.AddIndex(
            model_name='supplierpayoutbatch',
            index=models.Index(fields=['erpnext_sync_status', '-created_at'], name='supp_payout_erp_status'),
        ),
    ]
