# Generated by Django 4.2.29 on 2026-07-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_supplierpayableadjustment_erpnext_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierpayoutbatch',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='finance/payout-evidence/%Y/%m/'),
        ),
    ]
