# Generated by Django 4.2.29 on 2026-07-30 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('account_type', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=24)),
                ('is_group', models.BooleanField(default=False)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.accountingaccount')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='AccountingJournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('entry_type', models.CharField(choices=[('sales', 'Sales'), ('payment', 'Payment'), ('supplier_payable', 'Supplier Payable'), ('supplier_payout', 'Supplier Payout'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('posting_date', models.DateField()),
                ('memo', models.TextField(blank=True)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_accounting_journals', to=settings.AUTH_USER_MODEL)),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_accounting_journals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingPaymentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('receivable', 'Receivable'), ('payable', 'Payable')], max_length=16)),
                ('party_type', models.CharField(max_length=32)),
                ('party_id', models.CharField(max_length=64)),
                ('party_name', models.CharField(blank=True, max_length=160)),
                ('voucher_type', models.CharField(max_length=64)),
                ('voucher_no', models.CharField(max_length=128)),
                ('against_voucher_type', models.CharField(blank=True, max_length=64)),
                ('against_voucher_no', models.CharField(blank=True, max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('posting_date', models.DateField()),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_ledger_entries', to='accounting.accountingaccount')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_ledger_entries', to='accounting.accountingjournalentry')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-posting_date', '-id'],
                'indexes': [models.Index(fields=['account_type', 'party_type', 'party_id'], name='accounting__account_5eb37f_idx'), models.Index(fields=['voucher_type', 'voucher_no'], name='accounting__voucher_d62945_idx'), models.Index(fields=['against_voucher_type', 'against_voucher_no'], name='accounting__against_1fb28f_idx'), models.Index(fields=['source_content_type', 'source_object_id'], name='accounting__source__2cfc10_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountingJournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('party_type', models.CharField(blank=True, max_length=32)),
                ('party_id', models.CharField(blank=True, max_length=64)),
                ('party_name', models.CharField(blank=True, max_length=160)),
                ('against_account', models.CharField(blank=True, max_length=160)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.accountingaccount')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.accountingjournalentry')),
            ],
            options={
                'ordering': ['journal_entry_id', 'id'],
                'indexes': [models.Index(fields=['account', 'currency'], name='accounting__account_388ebe_idx'), models.Index(fields=['party_type', 'party_id'], name='accounting__party_t_2da704_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='accountingjournalentry',
            index=models.Index(fields=['status', '-posting_date'], name='accounting__status_e6d4fb_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingjournalentry',
            index=models.Index(fields=['entry_type', '-posting_date'], name='accounting__entry_t_b5103b_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingjournalentry',
            index=models.Index(fields=['source_content_type', 'source_object_id'], name='accounting__source__ab1bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['account_type', 'is_active'], name='accounting__account_338aca_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingaccount',
            index=models.Index(fields=['parent', 'code'], name='accounting__parent__bb123b_idx'),
        ),
    ]
