# Generated by Django 4.2.29 on 2026-07-30 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
        ('payments', '0009_alter_paymentproviderconfiguration_provider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingBankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField(db_index=True)),
                ('bank_account', models.CharField(default='Cash and Bank', max_length=160)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('transaction_id', models.CharField(blank=True, max_length=128, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('withdrawal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('status', models.CharField(choices=[('unreconciled', 'Unreconciled'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], db_index=True, default='unreconciled', max_length=16)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('import', 'Import'), ('gateway', 'Gateway')], default='manual', max_length=16)),
                ('clearance_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bank_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bank_transactions', to=settings.AUTH_USER_MODEL)),
                ('matched_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='order.order')),
                ('matched_payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='payments.paymentsession')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_bank_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AccountingReconciliationAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=16)),
                ('note', models.TextField(blank=True)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocations', to='accounting.accountingbanktransaction')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliation_allocations', to='accounting.accountingjournalentry')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_allocations', to='order.order')),
                ('payment_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_allocations', to='payments.paymentsession')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='accounting__status_91291a_idx'), models.Index(fields=['order', 'status'], name='accounting__order_i_a842d4_idx'), models.Index(fields=['payment_session', 'status'], name='accounting__payment_61d783_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='accountingbanktransaction',
            index=models.Index(fields=['status', '-transaction_date'], name='accounting__status_9bdd3a_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingbanktransaction',
            index=models.Index(fields=['provider', 'reference_number'], name='accounting__provide_0aaa45_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingbanktransaction',
            index=models.Index(fields=['matched_order', 'status'], name='accounting__matched_519c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingbanktransaction',
            index=models.Index(fields=['matched_payment_session', 'status'], name='accounting__matched_835662_idx'),
        ),
    ]
