# Generated by Django 4.2.29 on 2026-07-30 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_accountingbanktransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingbanktransaction',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
