# Generated by Django 4.2.29 on 2026-05-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotification',
            name='event_type',
            field=models.CharField(choices=[('account_registered', 'Account Registered'), ('email_verification', 'Email Verification'), ('email_two_factor', 'Email Two Factor'), ('password_reset', 'Password Reset'), ('password_changed', 'Password Changed'), ('quote_request_customer', 'Quote Request Customer'), ('quote_request_internal', 'Quote Request Internal'), ('order_confirmation', 'Order Confirmation'), ('shipping_update', 'Shipping Update')], max_length=64),
        ),
    ]
