import {
  AlertCircle,
  Archive,
  ArrowLeft,
  ArrowRight,
  BadgeCheck,
  BadgePercent,
  Ban,
  Banknote,
  Bell,
  BellOff,
  BookMarked,
  BookmarkPlus,
  BookmarkX,
  Building2,
  Camera,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleHelp,
  CircleOff,
  ClipboardCheck,
  Clock3,
  Contact,
  Copy,
  CreditCard,
  Edit3,
  ExternalLink,
  Eye,
  FileText,
  FolderInput,
  Gift,
  Heart,
  Home,
  ImageOff,
  Images,
  Inbox,
  Info,
  Landmark,
  LoaderCircle,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MailCheck,
  MailOpen,
  Map,
  MapPin,
  MapPinned,
  Megaphone,
  MessageCircle,
  MessageSquare,
  Minus,
  MoveHorizontal,
  MoveVertical,
  Navigation,
  Package,
  Package2,
  PanelTop,
  PencilLine,
  Phone,
  Plus,
  QrCode,
  RefreshCw,
  RotateCcw,
  Route,
  Save,
  Search,
  Send,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Tag,
  Trash2,
  Truck,
  User,
  UserCheck,
  UserCog,
  UserMinus,
  UserPlus,
  Users,
  WalletCards,
  Warehouse,
  Wrench
} from "lucide-react";

const iconMap = {
  account_balance: Landmark,
  account_balance_wallet: WalletCards,
  add: Plus,
  add_business: Building2,
  add_location_alt: MapPinned,
  add_shopping_cart: ShoppingCart,
  admin_panel_settings: ShieldCheck,
  alternate_email: Mail,
  apps: PanelTop,
  archive: Archive,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  block: Ban,
  bookmark_add: BookmarkPlus,
  bookmark_added: BookMarked,
  bookmark_remove: BookmarkX,
  campaign: Megaphone,
  cancel: CircleOff,
  category: PanelTop,
  chat: MessageCircle,
  check: Check,
  check_circle: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: CircleOff,
  company: Building2,
  confirmation_number: Gift,
  contacts: Contact,
  content_copy: Copy,
  country_code: Map,
  credit_card: CreditCard,
  current_password: Lock,
  delete: Trash2,
  done_all: CheckCheck,
  drive_file_move: FolderInput,
  edit: Edit3,
  email: Mail,
  engineering: Wrench,
  error: AlertCircle,
  fact_check: ClipboardCheck,
  favorite: Heart,
  first_name: User,
  forum: MessageSquare,
  heart_minus: Heart,
  history: Clock3,
  home: Home,
  hourglass_top: LoaderCircle,
  how_to_reg: UserCheck,
  image_not_supported: ImageOff,
  inbox: Inbox,
  info: Info,
  inventory: Package,
  inventory_2: Package2,
  ios_share: ExternalLink,
  is_default_for_billing: CreditCard,
  is_default_for_shipping: Truck,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  last_name: User,
  latitude: MapPin,
  line1: MapPin,
  line2: MapPin,
  line3: MapPin,
  line4: MapPin,
  local_offer: BadgePercent,
  local_shipping: Truck,
  location_label: MapPin,
  location_on: MapPin,
  lock: Lock,
  lock_reset: RotateCcw,
  login: LogIn,
  logout: LogOut,
  longitude: MapPin,
  mail: Mail,
  manage_accounts: UserCog,
  mark_email_read: MailCheck,
  mark_email_unread: MailOpen,
  message: MessageCircle,
  my_location: Navigation,
  name: User,
  new_password: Lock,
  new_password_confirm: Lock,
  new_releases: Sparkles,
  notes: FileText,
  notifications: Bell,
  notifications_active: Bell,
  notifications_off: BellOff,
  open_in_new: ExternalLink,
  order_number: FileText,
  outgoing_mail: Send,
  package_2: Package2,
  password: Lock,
  password_confirm: Lock,
  payments: Banknote,
  person: User,
  person_add: UserPlus,
  person_check: UserCheck,
  person_remove: UserMinus,
  phone: Phone,
  phone_iphone: Smartphone,
  phone_number: Phone,
  photo_camera: Camera,
  photo_library: Images,
  playlist_add: BookmarkPlus,
  postcode: MapPin,
  preferred_currency: Banknote,
  print: FileText,
  qr_code_2: QrCode,
  rate_review: PencilLine,
  receipt_long: FileText,
  receive_marketing_emails: Megaphone,
  receive_order_updates: Truck,
  refresh: RefreshCw,
  remove: Minus,
  replay: RotateCcw,
  request_quote: FileText,
  reviews: Star,
  route: Route,
  save: Save,
  science: Sparkles,
  search: Search,
  sell: Tag,
  send: Send,
  shield_lock: ShieldCheck,
  shopping_bag: ShoppingBag,
  shopping_cart: ShoppingCart,
  star: Star,
  state: Map,
  store: Store,
  storefront: Store,
  support_agent: Users,
  swap_horiz: MoveHorizontal,
  swap_vert: MoveVertical,
  sync: RefreshCw,
  tag: Tag,
  task_alt: CheckCircle2,
  title: FileText,
  travel_explore: Search,
  tune: SlidersHorizontal,
  two_factor_email_enabled: ShieldCheck,
  verified: BadgeCheck,
  verified_user: ShieldCheck,
  visibility: Eye,
  warehouse: Warehouse,
  warning: AlertCircle
};

const filledIcons = new Set([
  "favorite",
  "star",
  "check_circle",
  "task_alt",
  "verified",
  "verified_user",
  "mark_email_read",
  "notifications_active"
]);

export default function MaterialIcon({ name, size = 22, filled = false, className = "", title }) {
  const Icon = iconMap[name] || CircleHelp;
  const shouldFill = filled && filledIcons.has(name);

  return (
    <span
      className={`material-symbols-rounded ${className}`}
      aria-hidden={title ? undefined : "true"}
      title={title}
      style={{
        width: size,
        height: size,
        fontSize: size,
        flex: `0 0 ${size}px`
      }}
    >
      <Icon
        aria-hidden="true"
        size={size}
        strokeWidth={shouldFill ? 2.4 : 2.2}
        fill={shouldFill ? "currentColor" : "none"}
      />
    </span>
  );
}
