# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='MarketingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('placement', models.CharField(choices=[('home_hero', 'Homepage hero'), ('announcement', 'Announcement strip'), ('promo_banner', 'Promo banner'), ('featured', 'Featured block'), ('brand_strip', 'Brand strip')], db_index=True, max_length=40)),
                ('headline', models.CharField(blank=True, max_length=180)),
                ('body', models.TextField(blank=True)),
                ('eyebrow', models.CharField(blank=True, max_length=80)),
                ('image_url', models.URLField(blank=True)),
                ('image_alt', models.CharField(blank=True, max_length=160)),
                ('cta_text', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=240)),
                ('background_color', models.CharField(blank=True, max_length=24)),
                ('text_color', models.CharField(blank=True, max_length=24)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['placement', 'sort_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingblock',
            index=models.Index(fields=['placement', 'is_active', 'sort_order'], name='content_mar_placeme_162c56_idx'),
        ),
        migrations.AddIndex(
            model_name='marketingblock',
            index=models.Index(fields=['starts_at', 'ends_at'], name='content_mar_starts__7d4896_idx'),
        ),
    ]
