# Generated by Django 4.2.30 on 2026-05-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_marketingblock_image_url'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketingblock',
            new_name='content_mar_placeme_42a77c_idx',
            old_name='content_mar_placeme_162c56_idx',
        ),
        migrations.RenameIndex(
            model_name='marketingblock',
            new_name='content_mar_starts__61e065_idx',
            old_name='content_mar_starts__7d4896_idx',
        ),
    ]
