# Generated by Django 4.2.29 on 2026-05-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_content_mar_placeme_162c56_idx_content_mar_placeme_42a77c_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingblock',
            name='placement',
            field=models.CharField(choices=[('home_hero', 'Homepage hero'), ('announcement', 'Announcement strip'), ('promo_banner', 'Promo banner'), ('featured', 'Featured block'), ('brand_strip', 'Brand strip'), ('top_category', 'Top Category')], db_index=True, max_length=40),
        ),
    ]
