# Generated by Django 4.2.29 on 2026-07-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_marketingmediaasset'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='marketingmediaasset',
            new_name='content_mar_categor_375352_idx',
            old_name='content_mar_categor_f1e2f3_idx',
        ),
    ]
