# Generated by Django 4.2.29 on 2026-05-12 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email_two_factor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailtwofactorchallenge',
            new_name='accounts_em_user_id_fbe98a_idx',
            old_name='accounts_em_user_id_811832_idx',
        ),
        migrations.RenameIndex(
            model_name='emailtwofactorchallenge',
            new_name='accounts_em_expires_ce91c6_idx',
            old_name='accounts_em_expires_c83671_idx',
        ),
    ]
