# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_seed_admin_shipping_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='cash_on_delivery_allowed',
            field=models.BooleanField(default=False),
        ),
    ]
