# Generated by Django 4.2.29 on 2026-07-29 14:00

from django.db import migrations, models
import django.db.models.deletion


TAX_ATTRIBUTE_CODES = ['tax_status', 'charge_tax', 'tax_profile', 'tax_exemption_reason']
VALID_TAX_STATUSES = {'taxable', 'tax_exempt', 'zero_rated'}


def attribute_value_text(value):
    for field in (
        'value_text',
        'value_boolean',
        'value_integer',
        'value_float',
        'value_richtext',
        'value_date',
        'value_datetime',
    ):
        raw_value = getattr(value, field, None)
        if raw_value not in (None, ''):
            return str(raw_value).strip().lower()

    option = getattr(value, 'value_option', None)
    if option:
        return (getattr(option, 'option', '') or str(option)).strip().lower()

    return ''


def migrate_tax_attributes_to_config(apps, schema_editor):
    Product = apps.get_model('catalogue', 'Product')
    ProductAttributeValue = apps.get_model('catalogue', 'ProductAttributeValue')
    ProductTaxConfiguration = apps.get_model('accounts', 'ProductTaxConfiguration')

    values = (
        ProductAttributeValue.objects
        .filter(attribute__code__in=['tax_status', 'charge_tax'])
        .select_related('attribute')
        .order_by('product_id', 'attribute__code')
    )
    by_product = {}
    for value in values:
        text = attribute_value_text(value)
        by_product.setdefault(value.product_id, {})[value.attribute.code] = text

    configs = []
    for product_id in Product.objects.values_list('id', flat=True):
        attrs = by_product.get(product_id, {})
        status = attrs.get('tax_status') or ''
        if status not in VALID_TAX_STATUSES:
            charge_tax = attrs.get('charge_tax') or ''
            status = 'tax_exempt' if charge_tax in {'false', '0', 'no', 'off'} else 'taxable'
        configs.append(ProductTaxConfiguration(product_id=product_id, status=status))

    ProductTaxConfiguration.objects.bulk_create(configs, ignore_conflicts=True, batch_size=1000)
    ProductAttributeValue.objects.filter(attribute__code__in=TAX_ATTRIBUTE_CODES).delete()


def reverse_tax_config_migration(apps, schema_editor):
    ProductTaxConfiguration = apps.get_model('accounts', 'ProductTaxConfiguration')
    ProductAttribute = apps.get_model('catalogue', 'ProductAttribute')
    ProductAttributeValue = apps.get_model('catalogue', 'ProductAttributeValue')

    for config in ProductTaxConfiguration.objects.select_related('product', 'product__product_class').iterator():
        product = config.product
        product_class = getattr(product, 'product_class', None)
        if not product_class:
            continue
        attribute, _ = ProductAttribute.objects.get_or_create(
            product_class=product_class,
            code='tax_status',
            defaults={'name': 'Tax Status', 'type': ProductAttribute.TEXT, 'required': False},
        )
        ProductAttributeValue.objects.update_or_create(
            product=product,
            attribute=attribute,
            defaults={'value_text': config.status},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('accounts', '0014_customerprofile_cash_on_delivery_allowed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('taxable', 'Taxable'), ('tax_exempt', 'Tax exempt'), ('zero_rated', 'Zero-rated')], default='taxable', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='catalogue.product')),
            ],
            options={
                'ordering': ['product_id'],
                'indexes': [models.Index(fields=['status'], name='accounts_pr_status_e9f5a3_idx')],
            },
        ),
        migrations.RunPython(migrate_tax_attributes_to_config, reverse_tax_config_migration),
    ]
