# Generated by Django 4.2.29 on 2026-03-24 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[('erpnext', 'ERPNext')], default='erpnext', max_length=32)),
                ('base_url', models.URLField()),
                ('auth_type', models.CharField(choices=[('token', 'Token')], default='token', max_length=16)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('default_company', models.CharField(blank=True, max_length=255)),
                ('default_warehouse', models.CharField(blank=True, max_length=255)),
                ('poll_interval_minutes', models.PositiveIntegerField(default=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('error', 'Error'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_successful_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_failed_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_connections', to='partner.partner')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('products_import', 'Products Import'), ('stock_import', 'Stock Import'), ('prices_import', 'Prices Import'), ('customers_import', 'Customers Import'), ('suppliers_import', 'Suppliers Import'), ('orders_export', 'Orders Export'), ('fulfillment_import', 'Fulfillment Import'), ('connection_test', 'Connection Test')], max_length=32)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('cursor', models.CharField(blank=True, max_length=255)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='integrations.integrationconnection')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integration_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SyncEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=16)),
                ('entity_type', models.CharField(blank=True, max_length=32)),
                ('external_reference', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('payload_excerpt', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_logs', to='integrations.integrationconnection')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_logs', to='integrations.syncjob')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('product', 'Product'), ('warehouse', 'Warehouse'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('order', 'Order'), ('price', 'Price'), ('stock', 'Stock')], max_length=32)),
                ('external_id', models.CharField(max_length=255)),
                ('internal_model', models.CharField(max_length=120)),
                ('internal_id', models.CharField(max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.integrationconnection')),
            ],
            options={
                'ordering': ['connection_id', 'entity_type', 'external_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='integrationmapping',
            constraint=models.UniqueConstraint(fields=('connection', 'entity_type', 'external_id'), name='uniq_integration_mapping_external'),
        ),
    ]
