# Generated by Django 4.2.29 on 2026-03-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationmapping',
            name='entity_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('warehouse', 'Warehouse'), ('customer', 'Customer'), ('supplier', 'Supplier'), ('order', 'Order'), ('price', 'Price'), ('stock', 'Stock')], max_length=32),
        ),
    ]
