# Generated by Django 4.2.29 on 2026-03-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationmapping_entity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationconnection',
            name='credential_source',
            field=models.CharField(choices=[('db', 'Database'), ('env', 'Environment Variables')], default='db', max_length=16),
        ),
        migrations.AddField(
            model_name='integrationconnection',
            name='secret_env_prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
