# Generated by Codex on 2026-08-07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('integrations', '0003_integrationconnection_credential_source_and_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleMerchantProductSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=255)),
                ('content_language', models.CharField(default='en', max_length=16)),
                ('feed_label', models.CharField(default='KE', max_length=64)),
                ('product_input_name', models.CharField(blank=True, max_length=512)),
                ('processed_product_name', models.CharField(blank=True, max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('deleted', 'Deleted'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('last_action', models.CharField(choices=[('insert', 'Insert or update'), ('delete', 'Delete'), ('skip', 'Skip')], default='insert', max_length=16)),
                ('last_payload', models.JSONField(blank=True, default=dict)),
                ('last_response', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_merchant_product_syncs', to='integrations.integrationconnection')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_merchant_syncs', to='catalogue.product')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='googlemerchantproductsync',
            constraint=models.UniqueConstraint(fields=('connection', 'product'), name='uniq_google_merchant_sync_product'),
        ),
        migrations.AddConstraint(
            model_name='googlemerchantproductsync',
            constraint=models.UniqueConstraint(fields=('connection', 'content_language', 'feed_label', 'offer_id'), name='uniq_google_merchant_sync_offer'),
        ),
    ]
