# Generated by Django 4.2.30 on 2026-08-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_google_merchant_product_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationconnection',
            name='auth_type',
            field=models.CharField(choices=[('token', 'Token'), ('bearer', 'Bearer token'), ('service_account', 'Service account')], default='token', max_length=16),
        ),
        migrations.AlterField(
            model_name='integrationconnection',
            name='connection_type',
            field=models.CharField(choices=[('erpnext', 'ERPNext'), ('google_merchant', 'Google Merchant')], default='erpnext', max_length=32),
        ),
    ]
