from django.conf import settings


def build_api_docs() -> dict:
    base_url = '/api/v1'
    return {
        'title': 'Vortexus Backend API',
        'version': '1.0',
        'base_url': base_url,
        'summary': 'Backend API for industrial ecommerce covering catalog, search, checkout, payments, marketplace, and operations.',
        'authentication': {
            'session_auth': True,
            'csrf_required_for_mutations': True,
            'dashboard_staff_required': 'All /api/v1/admin/ endpoints require an authenticated staff user session and return 401/403 for unauthenticated or non-staff users.',
            'flow': [
                'GET /api/v1/account/csrf/ to obtain csrf_token',
                'Send session cookie with credentials on subsequent requests',
                'Include X-CSRFToken header on POST, PUT, PATCH, DELETE requests',
            ],
        },
        'response_contracts': {
            'errors': {
                'shape': {
                    'error': {
                        'code': 'validation_error',
                        'detail': 'Request validation failed.',
                        'status': 400,
                        'errors': {'field': ['message']},
                    }
                }
            },
            'throttled': {
                'shape': {
                    'error': {
                        'code': 'throttled',
                        'detail': 'Request was throttled. Expected available in 3600 seconds.',
                        'status': 429,
                        'retry_after_seconds': 3600,
                    }
                }
            },
        },
        'environment': {
            'async_enabled': bool(getattr(settings, 'ENABLE_ASYNC_TASKS', False)),
            'default_currency': settings.OSCAR_DEFAULT_CURRENCY,
            'payment_methods': [method['code'] for method in settings.PAYMENT_METHODS],
        },
        'sections': [
            {
                'name': 'Health',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/health/live/',
                        'auth': 'public',
                        'description': 'Simple liveness probe.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/health/ready/',
                        'auth': 'public',
                        'description': 'Readiness/dependency probe for database, cache, OpenSearch, and async mode.',
                    },
                ],
            },
            {
                'name': 'Account',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/account/csrf/',
                        'auth': 'public',
                        'description': 'Fetch CSRF token for session-authenticated API usage.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/account/register/',
                        'auth': 'public',
                        'description': 'Register a customer account and start a session.',
                        'request_example': {
                            'email': 'buyer@example.com',
                            'password': 'Testpass123!',
                            'password_confirm': 'Testpass123!',
                            'first_name': 'Ronald',
                            'last_name': 'Ambundo',
                            'country_code': 'KE',
                        },
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/account/login/',
                        'auth': 'public',
                        'description': 'Login by username or email via identifier field.',
                        'request_example': {
                            'identifier': 'buyer@example.com',
                            'password': 'Testpass123!',
                        },
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/account/logout/',
                        'auth': 'session',
                        'description': 'Terminate the current authenticated session.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/account/me/',
                        'auth': 'session',
                        'description': 'Fetch current customer profile and settings.',
                    },
                    {
                        'method': 'PATCH',
                        'path': f'{base_url}/account/me/',
                        'auth': 'session',
                        'description': 'Update account profile fields and notification settings.',
                        'request_example': {
                            'first_name': 'Ronald',
                            'phone': '+254700000000',
                            'company': 'Vortexus',
                            'preferred_currency': 'KES',
                        },
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/account/password/',
                        'auth': 'session',
                        'description': 'Change the authenticated user password.',
                        'request_example': {
                            'current_password': 'OldPass123!',
                            'new_password': 'NewPass123!',
                            'new_password_confirm': 'NewPass123!',
                        },
                    },
                ],
            },
            {
                'name': 'Catalog And Search',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/catalog/categories/',
                        'auth': 'public',
                        'description': 'List top-level categories with immediate child categories.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/catalog/products/',
                        'auth': 'public',
                        'description': 'List/search public products with filters and pagination.',
                        'query_params': ['q', 'category', 'in_stock', 'min_price', 'max_price', 'sort_by', 'page', 'page_size'],
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/catalog/products/',
                        'auth': 'staff session',
                        'description': 'Create a catalog product.',
                        'request_example': {
                            'upc': 'PUMP-001',
                            'title': '3HP Borehole Pump',
                            'description': 'Industrial submersible pump',
                            'is_public': True,
                            'partner_name': 'Default Partner',
                            'price': '499.99',
                            'currency': 'USD',
                            'num_in_stock': 12,
                        },
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/catalog/products/<product_id>/',
                        'auth': 'public',
                        'description': 'Fetch product detail and related products.',
                    },
                    {
                        'method': 'PATCH',
                        'path': f'{base_url}/catalog/products/<product_id>/',
                        'auth': 'staff session',
                        'description': 'Partially update a catalog product.',
                    },
                    {
                        'method': 'DELETE',
                        'path': f'{base_url}/catalog/products/<product_id>/',
                        'auth': 'staff session',
                        'description': 'Delete a catalog product.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/search/',
                        'auth': 'public',
                        'description': 'Text search over products.',
                        'query_params': ['q', 'category', 'in_stock', 'min_price', 'max_price', 'sort_by', 'page', 'page_size'],
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/search/suggestions/',
                        'auth': 'public',
                        'description': 'Lightweight product search suggestions/autocomplete.',
                        'query_params': ['q', 'category', 'limit'],
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/search/image/',
                        'auth': 'public',
                        'description': 'Multipart image similarity search.',
                        'content_type': 'multipart/form-data',
                        'form_fields': ['image', 'category', 'top_k'],
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/recommendations/',
                        'auth': 'public',
                        'description': 'Get recommendations by product_id, user_id, or trending fallback.',
                        'query_params': ['product_id', 'user_id', 'limit'],
                    },
                ],
            },
            {
                'name': 'Checkout',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/checkout/basket/',
                        'auth': 'public session',
                        'description': 'Fetch current basket, totals, and reservation-aware basket lines.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/basket/items/',
                        'auth': 'public session',
                        'description': 'Add an item to the basket.',
                        'request_example': {'product_id': 1, 'quantity': 2},
                    },
                    {
                        'method': 'PATCH',
                        'path': f'{base_url}/checkout/basket/items/<line_id>/',
                        'auth': 'public session',
                        'description': 'Update basket line quantity.',
                        'request_example': {'quantity': 3},
                    },
                    {
                        'method': 'PUT',
                        'path': f'{base_url}/checkout/shipping/address/',
                        'auth': 'public session',
                        'description': 'Save shipping address for the active checkout session.',
                        'request_example': {
                            'first_name': 'Ronald',
                            'last_name': 'Ambundo',
                            'line1': 'Westlands Road',
                            'line4': 'Nairobi',
                            'country_code': 'KE',
                            'phone_number': '+254700000000',
                        },
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/shipping/select/',
                        'auth': 'public session',
                        'description': 'Select one available shipping method.',
                        'request_example': {'method_code': 'standard-freight'},
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/checkout/shipping/',
                        'auth': 'public session',
                        'description': 'Get checkout basket, address, methods, shipping metrics, and totals.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/orders/',
                        'auth': 'public session',
                        'description': 'Place an order from the current basket.',
                        'request_example': {
                            'guest_email': 'buyer@example.com',
                            'payment_reference': 'PAY-ABC123DEF456',
                        },
                    },
                ],
            },
            {
                'name': 'Payments',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/checkout/payments/methods/',
                        'auth': 'public session',
                        'description': 'List supported payment methods and requirements.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/payments/',
                        'auth': 'public session',
                        'description': 'Initialize a generic payment session.',
                        'request_example': {'method': 'cash_on_delivery', 'payer_email': 'buyer@example.com'},
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/payments/mpesa/initiate/',
                        'auth': 'public session',
                        'description': 'Initialize M-Pesa payment for the current basket.',
                        'request_example': {'phone_number': '+254700000011', 'payer_email': 'buyer@example.com'},
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/payments/airtel-money/initiate/',
                        'auth': 'public session',
                        'description': 'Initialize Airtel Money payment for the current basket.',
                        'request_example': {'phone_number': '+254700000011', 'payer_email': 'buyer@example.com'},
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/payments/cards/initiate/',
                        'auth': 'public session',
                        'description': 'Initialize credit/debit card payment using tokenized card data.',
                        'request_example': {
                            'method': 'credit_card',
                            'payer_email': 'buyer@example.com',
                            'payment_token': 'tok_test_visa',
                            'card_brand': 'visa',
                            'last4': '4242',
                            'expiry_month': 12,
                            'expiry_year': 2030,
                            'holder_name': 'Card Buyer',
                        },
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/checkout/payments/<reference>/',
                        'auth': 'public session',
                        'description': 'Fetch payment session state.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/checkout/payments/<reference>/confirm/',
                        'auth': 'public session',
                        'description': 'Confirm payment session for sandbox/testing callbacks.',
                        'request_example': {'success': True, 'external_reference': 'TXN-123'},
                    },
                ],
            },
            {
                'name': 'Orders',
                'endpoints': [
                    {
                        'method': 'GET',
                        'path': f'{base_url}/account/orders/',
                        'auth': 'session',
                        'description': 'List current user orders.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/account/orders/<order_number>/',
                        'auth': 'session',
                        'description': 'Fetch current user order detail.',
                    },
                    {
                        'method': 'GET',
                        'path': f'{base_url}/account/orders/<order_number>/status/',
                        'auth': 'session',
                        'description': 'Fetch order status timeline.',
                    },
                    {
                        'method': 'POST',
                        'path': f'{base_url}/account/orders/<order_number>/reorder/',
                        'auth': 'session',
                        'description': 'Re-add previous order items to the active basket.',
                    },
                ],
            },
            {
                'name': 'Wishlist And Reviews',
                'endpoints': [
                    {'method': 'GET', 'path': f'{base_url}/account/wishlist/', 'auth': 'session', 'description': 'Get default saved-items wishlist.'},
                    {'method': 'POST', 'path': f'{base_url}/account/wishlist/items/', 'auth': 'session', 'description': 'Add product to default wishlist.', 'request_example': {'product_id': 1}},
                    {'method': 'DELETE', 'path': f'{base_url}/account/wishlist/items/<product_id>/', 'auth': 'session', 'description': 'Remove product from default wishlist.'},
                    {'method': 'POST', 'path': f'{base_url}/account/wishlist/status/', 'auth': 'session', 'description': 'Check wishlist membership for product ids.', 'request_example': {'product_ids': [1, 2, 3]}},
                    {'method': 'GET', 'path': f'{base_url}/account/wishlists/', 'auth': 'session', 'description': 'List named wishlists.'},
                    {'method': 'POST', 'path': f'{base_url}/account/wishlists/', 'auth': 'session', 'description': 'Create named wishlist.', 'request_example': {'name': 'Project Phase 1'}},
                    {'method': 'GET', 'path': f'{base_url}/catalog/products/<product_id>/reviews/', 'auth': 'public', 'description': 'List public reviews for a product.'},
                    {'method': 'POST', 'path': f'{base_url}/catalog/products/<product_id>/reviews/', 'auth': 'session', 'description': 'Create product review.', 'request_example': {'title': 'Reliable pump', 'score': 5, 'body': 'Performed well on site.'}},
                    {'method': 'GET', 'path': f'{base_url}/account/reviews/', 'auth': 'session', 'description': 'List current user reviews.'},
                ],
            },
            {
                'name': 'Supplier Marketplace',
                'endpoints': [
                    {'method': 'GET', 'path': f'{base_url}/supplier/profile/', 'auth': 'session', 'description': 'Fetch supplier profile/applicability state.'},
                    {'method': 'POST', 'path': f'{base_url}/supplier/profile/', 'auth': 'session', 'description': 'Create supplier profile application.'},
                    {'method': 'PATCH', 'path': f'{base_url}/supplier/profile/', 'auth': 'session', 'description': 'Update supplier profile.'},
                    {'method': 'GET', 'path': f'{base_url}/supplier/dashboard/', 'auth': 'supplier session', 'description': 'Fetch supplier dashboard metrics.'},
                    {'method': 'GET', 'path': f'{base_url}/supplier/orders/', 'auth': 'supplier session', 'description': 'List supplier-visible order groups.'},
                    {'method': 'GET', 'path': f'{base_url}/supplier/orders/<order_number>/', 'auth': 'supplier session', 'description': 'Fetch supplier order detail.'},
                    {'method': 'POST', 'path': f'{base_url}/supplier/orders/<order_number>/lines/<line_id>/status/', 'auth': 'approved supplier session', 'description': 'Update supplier-owned line fulfillment status.', 'request_example': {'status': 'shipped', 'tracking_reference': 'TRK-1001'}},
                    {'method': 'GET', 'path': f'{base_url}/supplier/products/', 'auth': 'supplier session', 'description': 'List supplier-owned offers/products.'},
                    {'method': 'POST', 'path': f'{base_url}/supplier/products/', 'auth': 'approved supplier session', 'description': 'Create supplier-owned product/offer.'},
                ],
            },
            {
                'name': 'Admin',
                'endpoints': [
                    {'method': 'GET', 'path': f'{base_url}/admin/suppliers/', 'auth': 'staff session', 'description': 'List supplier profiles with user and partner metadata for approval workflow.', 'query_params': ['status']},
                    {'method': 'GET', 'path': f'{base_url}/admin/suppliers/<supplier_id>/', 'auth': 'staff session', 'description': 'Fetch a single supplier profile with contact, status, linked user, and partner details.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/suppliers/<supplier_id>/', 'auth': 'staff session', 'description': 'Update supplier approval status and editable profile fields. Updating company_name also updates the linked partner name.', 'request_example': {'status': 'approved', 'company_name': 'Norwa Supplies', 'contact_name': 'Procurement Lead', 'phone': '+254700000000', 'country_code': 'KE', 'website': 'https://example.com', 'notes': 'Approved after document review.'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/audit-logs/', 'auth': 'staff session', 'description': 'List audit log entries with filtering by event, actor, target, path, status, search text, and date range.', 'query_params': ['q', 'event_type', 'actor_email', 'target_type', 'target_id', 'path', 'status', 'date_from', 'date_to', 'page', 'page_size']},
                    {'method': 'GET', 'path': f'{base_url}/admin/audit-logs/<audit_log_id>/', 'auth': 'staff session', 'description': 'Fetch single audit log record.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/dashboard/', 'auth': 'staff session', 'description': 'Fetch live dashboard KPIs, sales/revenue trend, latest orders, product mix, and stock alerts.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/campaigns/', 'auth': 'staff session', 'description': 'Fetch database-backed campaign opportunities from quote leads, pending orders, stock, draft products, and sales signals.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/support/', 'auth': 'staff session', 'description': 'Fetch support workload from quote notifications and order cases requiring admin attention.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/categories/', 'auth': 'staff session', 'description': 'List admin category tree rows with pagination, including parent/depth/child counts and visibility fields.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/catalog/categories/', 'auth': 'staff session', 'description': 'Create a root catalog category.', 'request_example': {'name': 'Pumps', 'slug': 'pumps', 'description': 'Pump equipment and accessories.', 'is_public': True}},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/categories/<category_id>/', 'auth': 'staff session', 'description': 'Fetch a single catalog category.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/catalog/categories/<category_id>/', 'auth': 'staff session', 'description': 'Update category name, slug, description, or storefront visibility.', 'request_example': {'name': 'Industrial Pumps', 'is_public': True}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/catalog/categories/<category_id>/', 'auth': 'staff session', 'description': 'Delete a catalog category.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/catalog/categories/<category_id>/children/', 'auth': 'staff session', 'description': 'Create a child category under an existing parent category.', 'request_example': {'name': 'Submersible Pumps', 'slug': 'submersible-pumps', 'is_public': True}},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/product-types/', 'auth': 'staff session', 'description': 'List Oscar product classes/types with shipping and stock behavior flags.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/catalog/product-types/', 'auth': 'staff session', 'description': 'Create a product type/class.', 'request_example': {'name': 'Physical product', 'slug': 'physical-product', 'requires_shipping': True, 'track_stock': True}},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/product-types/<product_type_id>/', 'auth': 'staff session', 'description': 'Fetch a single product type/class.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/catalog/product-types/<product_type_id>/', 'auth': 'staff session', 'description': 'Update product type/class name, slug, shipping flag, or stock tracking flag.', 'request_example': {'requires_shipping': False, 'track_stock': False}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/catalog/product-types/<product_type_id>/', 'auth': 'staff session', 'description': 'Delete a product type/class.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/attributes/', 'auth': 'staff session', 'description': 'List product attributes with product type, code, data type, required flag, and option group metadata.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/catalog/attributes/', 'auth': 'staff session', 'description': 'Create an attribute for a product type/class.', 'request_example': {'product_class_id': 1, 'name': 'Brand', 'code': 'brand', 'type': 'text', 'required': False}},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/attributes/<attribute_id>/', 'auth': 'staff session', 'description': 'Fetch a single product attribute.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/catalog/attributes/<attribute_id>/', 'auth': 'staff session', 'description': 'Update attribute name, code, data type, or required flag.', 'request_example': {'name': 'Manufacturer brand', 'required': True}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/catalog/attributes/<attribute_id>/', 'auth': 'staff session', 'description': 'Delete a product attribute.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/options/', 'auth': 'staff session', 'description': 'List product options with code, data type, required flag, help text, and display order.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/catalog/options/', 'auth': 'staff session', 'description': 'Create a product option used for customer-supplied purchase choices.', 'request_example': {'name': 'Custom label', 'code': 'custom_label', 'type': 'text', 'required': False, 'help_text': 'Text to print on the label.', 'order': 10}},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/options/<option_id>/', 'auth': 'staff session', 'description': 'Fetch a single product option.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/catalog/options/<option_id>/', 'auth': 'staff session', 'description': 'Update option name, code, data type, required flag, help text, or display order.', 'request_example': {'required': True, 'order': 20}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/catalog/options/<option_id>/', 'auth': 'staff session', 'description': 'Delete a product option.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/catalog/stock-alerts/', 'auth': 'staff session', 'description': 'List stock alerts with status, threshold, dates, product, SKU, and current stock metadata.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/catalog/stock-alerts/<alert_id>/', 'auth': 'staff session', 'description': 'Update a stock alert workflow status. Setting status to closed records date_closed.', 'request_example': {'status': 'closed'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/vouchers/', 'auth': 'staff session', 'description': 'List Oscar vouchers with usage policy, validity window, basket/order counts, discount totals, and linked offers.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/vouchers/', 'auth': 'staff session', 'description': 'Create an Oscar voucher/coupon code.', 'request_example': {'name': 'May Campaign', 'code': 'MAY10', 'usage': 'Multi-use', 'start_datetime': '2026-05-01T00:00:00', 'end_datetime': '2026-05-31T23:59:00'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/vouchers/<voucher_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar voucher with linked offers.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/vouchers/<voucher_id>/', 'auth': 'staff session', 'description': 'Update voucher name, code, usage policy, or validity window.', 'request_example': {'usage': 'Once per customer'}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/vouchers/<voucher_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar voucher.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/vouchers/<voucher_id>/stats/', 'auth': 'staff session', 'description': 'Fetch voucher monitoring totals including basket additions, orders, discount, and linked offers.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/vouchers/<voucher_id>/offers/', 'auth': 'staff session', 'description': 'List offers linked to a voucher.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/vouchers/<voucher_id>/offers/', 'auth': 'staff session', 'description': 'Attach an existing offer to a voucher. The offer type is converted to voucher offer when needed.', 'request_example': {'offer_id': 1}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/vouchers/<voucher_id>/offers/', 'auth': 'staff session', 'description': 'Remove an offer from a voucher.', 'request_example': {'offer_id': 1}},
                    {'method': 'GET', 'path': f'{base_url}/admin/ranges/', 'auth': 'staff session', 'description': 'List Oscar ranges with visibility, all-product matching flag, and product counts.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/ranges/', 'auth': 'staff session', 'description': 'Create a product range for offers or merchandising.', 'request_example': {'name': 'Featured Pumps', 'slug': 'featured-pumps', 'description': 'Promoted pump collection.', 'is_public': True, 'includes_all_products': False}},
                    {'method': 'GET', 'path': f'{base_url}/admin/ranges/<range_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar range.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/ranges/<range_id>/', 'auth': 'staff session', 'description': 'Update range name, slug, description, visibility, or all-product matching flag.', 'request_example': {'is_public': False}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/ranges/<range_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar range.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/ranges/<range_id>/products/', 'auth': 'staff session', 'description': 'List products currently assigned to a range.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/ranges/<range_id>/products/', 'auth': 'staff session', 'description': 'Add a product to a range.', 'request_example': {'product_id': 1}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/ranges/<range_id>/products/', 'auth': 'staff session', 'description': 'Remove a product from a range.', 'request_example': {'product_id': 1}},
                    {'method': 'GET', 'path': f'{base_url}/admin/reviews/', 'auth': 'staff session', 'description': 'List product reviews for moderation with product, customer, score, status, and created date metadata.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/reviews/<review_id>/', 'auth': 'staff session', 'description': 'Fetch a single product review for moderation.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/reviews/<review_id>/', 'auth': 'staff session', 'description': 'Update review moderation status, title, body, or score. Status values are 0 requires moderation, 1 approved, and 2 rejected.', 'request_example': {'status': 1}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/reviews/<review_id>/', 'auth': 'staff session', 'description': 'Delete a product review.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/partners/', 'auth': 'staff session', 'description': 'List Oscar partners with code and linked user counts.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/partners/', 'auth': 'staff session', 'description': 'Create an Oscar partner/supplier record.', 'request_example': {'name': 'Norwa Supplies', 'code': 'norwa-supplies'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/partners/<partner_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar partner.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/partners/<partner_id>/', 'auth': 'staff session', 'description': 'Update partner name or code.', 'request_example': {'name': 'Norwa Industrial Supplies'}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/partners/<partner_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar partner.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/partners/<partner_id>/users/', 'auth': 'staff session', 'description': 'List dashboard users linked to a partner.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/partners/<partner_id>/users/', 'auth': 'staff session', 'description': 'Link a user to a partner by request body.', 'request_example': {'user_id': 1}},
                    {'method': 'POST', 'path': f'{base_url}/admin/partners/<partner_id>/users/<user_id>/link/', 'auth': 'staff session', 'description': 'Link a specific user to a partner.'},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/partners/<partner_id>/users/<user_id>/unlink/', 'auth': 'staff session', 'description': 'Unlink a specific user from a partner.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/shipping/weight-based/', 'auth': 'staff session', 'description': 'List Oscar weight-based shipping methods with nested rate bands.', 'query_params': ['page', 'page_size']},
                    {'method': 'POST', 'path': f'{base_url}/admin/shipping/weight-based/', 'auth': 'staff session', 'description': 'Create a weight-based shipping method.', 'request_example': {'name': 'Standard Freight', 'code': 'standard-freight', 'description': 'Standard delivery by basket weight.', 'default_weight': '1.000'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/', 'auth': 'staff session', 'description': 'Fetch a single weight-based shipping method with bands.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/', 'auth': 'staff session', 'description': 'Update shipping method code, name, description, or default weight.', 'request_example': {'default_weight': '2.500'}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/', 'auth': 'staff session', 'description': 'Delete a weight-based shipping method.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/bands/', 'auth': 'staff session', 'description': 'Create a weight band for a shipping method.', 'request_example': {'upper_limit': '10.000', 'charge': '15.00'}},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/bands/<band_id>/', 'auth': 'staff session', 'description': 'Update a weight band upper limit or charge.', 'request_example': {'charge': '20.00'}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/shipping/weight-based/<method_id>/bands/<band_id>/', 'auth': 'staff session', 'description': 'Delete a weight band.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/meta/', 'auth': 'staff session', 'description': 'Fetch offer type, status, condition type, and benefit type choices for dashboard forms.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/conditions/', 'auth': 'staff session', 'description': 'List Oscar offer conditions with type, range, value, proxy class, and display description.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/offers/conditions/', 'auth': 'staff session', 'description': 'Create an Oscar offer condition.', 'request_example': {'type': 'Count', 'range_id': 1, 'value': 2}},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/conditions/<condition_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar offer condition.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/offers/conditions/<condition_id>/', 'auth': 'staff session', 'description': 'Update an Oscar offer condition.', 'request_example': {'value': 3}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/offers/conditions/<condition_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar offer condition.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/benefits/', 'auth': 'staff session', 'description': 'List Oscar offer benefits with type, range, value, max affected items, proxy class, and display description.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/offers/benefits/', 'auth': 'staff session', 'description': 'Create an Oscar offer benefit.', 'request_example': {'type': 'Percentage', 'range_id': 1, 'value': 10, 'max_affected_items': 1}},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/benefits/<benefit_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar offer benefit.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/offers/benefits/<benefit_id>/', 'auth': 'staff session', 'description': 'Update an Oscar offer benefit.', 'request_example': {'value': 15}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/offers/benefits/<benefit_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar offer benefit.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/', 'auth': 'staff session', 'description': 'List Oscar conditional offers with condition, benefit, voucher linkage, status, priority, and usage totals.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/offers/', 'auth': 'staff session', 'description': 'Create an Oscar conditional offer linked to an existing condition and benefit.', 'request_example': {'name': '10% off pumps', 'offer_type': 'Site', 'condition_id': 1, 'benefit_id': 1, 'status': 'Open', 'priority': 0}},
                    {'method': 'GET', 'path': f'{base_url}/admin/offers/<offer_id>/', 'auth': 'staff session', 'description': 'Fetch a single Oscar conditional offer.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/offers/<offer_id>/', 'auth': 'staff session', 'description': 'Update offer details, schedule, condition, benefit, priority, exclusivity, or status.', 'request_example': {'status': 'Suspended', 'priority': 10}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/offers/<offer_id>/', 'auth': 'staff session', 'description': 'Delete an Oscar conditional offer.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/offers/<offer_id>/status/', 'auth': 'staff session', 'description': 'Update only the offer workflow status.', 'request_example': {'status': 'Open'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/users/', 'auth': 'staff session', 'description': 'List users with search, role/status filtering, pagination, and summary metrics.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/users/', 'auth': 'staff session', 'description': 'Create a customer, staff, or admin account.', 'request_example': {'email': 'operator@example.com', 'password': 'TempPass123!', 'first_name': 'Ops', 'last_name': 'User', 'role': 'staff', 'status': 'active'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/users/<user_id>/', 'auth': 'staff session', 'description': 'Fetch admin user detail including profile, access flags, and supplier state.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/users/<user_id>/', 'auth': 'staff session', 'description': 'Update user profile basics, access role, status, or password.', 'request_example': {'status': 'suspended', 'company': 'SiteWorks Ltd'}},
                    {'method': 'POST', 'path': f'{base_url}/admin/users/<user_id>/password-reset/', 'auth': 'staff session', 'description': 'Generate a password reset uid/token payload for a user support flow.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/users/<user_id>/product-alerts/', 'auth': 'staff session', 'description': 'List product stock alerts linked to a user account.'},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/users/<user_id>/product-alerts/<alert_id>/', 'auth': 'staff session', 'description': 'Cancel a user product alert when it is active or unconfirmed.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/media/', 'auth': 'staff session', 'description': 'List product media assets with search, product filtering, and pagination.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/media/', 'auth': 'staff session', 'description': 'Upload an image asset and attach it to a product. Uses the backend image validation/compression pipeline.', 'request_example': {'product_id': 1, 'alt': 'Pump product image', 'image': '<multipart file>'}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/media/<image_id>/', 'auth': 'staff session', 'description': 'Delete a product media asset.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/settings/', 'auth': 'staff session', 'description': 'Fetch editable admin dashboard settings, logged-in admin profile, and read-only runtime store configuration.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/settings/', 'auth': 'staff session', 'description': 'Update editable store site fields and logged-in admin profile preferences.', 'request_example': {'store': {'site_name': 'Vortexus', 'site_domain': 'admin.example.com'}, 'profile': {'first_name': 'Ronald', 'receive_order_updates': True}}},
                    {'method': 'GET', 'path': f'{base_url}/admin/orders/', 'auth': 'staff session', 'description': 'List admin-visible orders with search, status filtering, pagination, and summary metrics.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/orders/<order_id>/', 'auth': 'staff session', 'description': 'Fetch admin order detail including customer, totals, tracking, and supplier groups.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/orders/<order_id>/status/', 'auth': 'staff session', 'description': 'Update order workflow status, add tracking reference, and record an internal note.', 'request_example': {'status': 'Shipped', 'tracking_reference': 'TRK-1001', 'note': 'Released from warehouse'}} ,
                    {'method': 'GET', 'path': f'{base_url}/admin/orders/<order_number>/lines/<line_id>/', 'auth': 'staff session', 'description': 'Fetch a single order line with product title, UPC, quantity, partner, SKU, status, unit prices, and line totals.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/orders/<order_number>/shipping-address/', 'auth': 'staff session', 'description': 'Update an order shipping address and delivery notes.', 'request_example': {'first_name': 'Ronald', 'last_name': 'Ambundo', 'line1': 'Westlands Road', 'line4': 'Nairobi', 'country_code': 'KE', 'phone_number': '+254700000000', 'notes': 'Call before delivery.'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/orders/<order_number>/notes/', 'auth': 'staff session', 'description': 'List internal notes recorded against an order.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/orders/<order_number>/notes/', 'auth': 'staff session', 'description': 'Create an internal order note.', 'request_example': {'note_type': 'Admin', 'message': 'Customer confirmed updated delivery address.'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/reports/', 'auth': 'staff session', 'description': 'List available operational report definitions including orders, products, customers, and vouchers.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/reports/<report_name>/', 'auth': 'staff session', 'description': 'Fetch a paginated operational report with report-specific summary metrics and rows.', 'query_params': ['page', 'page_size']},
                    {'method': 'GET', 'path': f'{base_url}/admin/pages/', 'auth': 'staff session', 'description': 'List CMS flat pages with URL, title, content, and access rule metadata.', 'query_params': ['page', 'page_size']},
                    {'method': 'POST', 'path': f'{base_url}/admin/pages/', 'auth': 'staff session', 'description': 'Create a CMS flat page and attach it to the current site.', 'request_example': {'url': '/about/', 'title': 'About Vortexus', 'content': 'Industrial ecommerce content.', 'registration_required': False}},
                    {'method': 'GET', 'path': f'{base_url}/admin/pages/<page_id>/', 'auth': 'staff session', 'description': 'Fetch a single CMS flat page.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/pages/<page_id>/', 'auth': 'staff session', 'description': 'Update CMS flat page URL, title, content, or access requirement.', 'request_example': {'title': 'Updated Page Title', 'registration_required': True}},
                    {'method': 'DELETE', 'path': f'{base_url}/admin/pages/<page_id>/', 'auth': 'staff session', 'description': 'Delete a CMS flat page.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/communications/', 'auth': 'staff session', 'description': 'List Oscar communication event templates with category, subject, email body, HTML body, and SMS body fields.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/communications/<slug>/', 'auth': 'staff session', 'description': 'Fetch a single communication event template by code.'},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/communications/<slug>/', 'auth': 'staff session', 'description': 'Update a communication event template name, category, email subject, text body, HTML body, or SMS body.', 'request_example': {'email_subject_template': 'Your order {{ order.number }} has shipped', 'sms_template': 'Order {{ order.number }} has shipped.'}},
                    {'method': 'GET', 'path': f'{base_url}/admin/integrations/', 'auth': 'staff session', 'description': 'List ERP/integration connections.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/integrations/', 'auth': 'staff session', 'description': 'Create an ERP/integration connection. Prefer credential_source=env with secret_env_prefix for production.', 'request_example': {'name': 'ERPNext Norwa', 'connection_type': 'erpnext', 'base_url': 'https://erp.example.com', 'auth_type': 'token', 'credential_source': 'env', 'secret_env_prefix': 'ERPNEXT_NORWA'}},
                    {'method': 'PATCH', 'path': f'{base_url}/admin/integrations/<connection_id>/', 'auth': 'staff session', 'description': 'Update an ERP/integration connection, including switching between database-backed and environment-backed credentials.'},
                    {'method': 'POST', 'path': f'{base_url}/admin/integrations/<connection_id>/erpnext/test/', 'auth': 'staff session', 'description': 'Test an ERPNext connection.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/integrations/<connection_id>/erpnext/preview/', 'auth': 'staff session', 'description': 'Preview ERPNext items, stock, or prices before importing.', 'query_params': ['resource: items|stock|prices', 'limit: 1-100']},
                    {'method': 'POST', 'path': f'{base_url}/admin/integrations/<connection_id>/erpnext/import/', 'auth': 'staff session', 'description': 'Import ERPNext item groups and items into categories and catalog, optionally refreshing stock in the same run.', 'request_example': {'include_stock': True}},
                    {'method': 'POST', 'path': f'{base_url}/admin/integrations/<connection_id>/erpnext/stock-sync/', 'auth': 'staff session', 'description': 'Sync ERPNext stock balances into stock records.'},
                    {'method': 'GET', 'path': f'{base_url}/admin/integrations/<connection_id>/logs/', 'auth': 'staff session', 'description': 'List recent integration logs.'},
                ],
            },
            {
                'name': 'Quotes',
                'endpoints': [
                    {
                        'method': 'POST',
                        'path': f'{base_url}/quotes/',
                        'auth': 'public',
                        'description': 'Submit a quote request with optional product reference.',
                        'request_example': {
                            'name': 'Project Engineer',
                            'email': 'engineer@example.com',
                            'phone': '+254700000000',
                            'company': 'SiteWorks Ltd',
                            'message': 'Need pricing for borehole pump + pressure tank.',
                            'product_id': 1,
                        },
                    }
                ],
            },
        ],
    }
