from django.urls import include, path

from .account_views import (
    AccountLoginAPIView,
    AccountLoginTwoFactorAPIView,
    AccountLogoutAPIView,
    AccountEmailVerificationResendAPIView,
    AccountEmailVerifyAPIView,
    AccountPasswordAPIView,
    AccountProfileAPIView,
    AccountReactivationRequestAPIView,
    AccountRegisterAPIView,
    CsrfTokenAPIView,
)
from .admin_extra_views import (
    AdminAttributeCollectionAPIView,
    AdminAttributeDetailAPIView,
    AdminCategoryChildrenAPIView,
    AdminCategoryCollectionAPIView,
    AdminCategoryDetailAPIView,
    AdminCommunicationCollectionAPIView,
    AdminCommunicationDetailAPIView,
    AdminDashboardSummaryAPIView,
    AdminLowStockAPIView,
    AdminOfferBenefitCollectionAPIView,
    AdminOfferBenefitDetailAPIView,
    AdminOfferCollectionAPIView,
    AdminOfferConditionCollectionAPIView,
    AdminOfferConditionDetailAPIView,
    AdminOfferDetailAPIView,
    AdminOfferMetadataAPIView,
    AdminOfferStatusAPIView,
    AdminOptionCollectionAPIView,
    AdminOptionDetailAPIView,
    AdminOrderLineDetailAPIView,
    AdminOrderNoteAPIView,
    AdminOrderShippingAddressAPIView,
    AdminOrderStatisticsAPIView,
    AdminPageCollectionAPIView,
    AdminPageDetailAPIView,
    AdminPartnerCollectionAPIView,
    AdminPartnerDetailAPIView,
    AdminPartnerUserCollectionAPIView,
    AdminPartnerUserLinkAPIView,
    AdminProductTypeCollectionAPIView,
    AdminProductTypeDetailAPIView,
    AdminRangeCollectionAPIView,
    AdminRangeDetailAPIView,
    AdminRangeProductAPIView,
    AdminReportAPIView,
    AdminReportListAPIView,
    AdminReviewCollectionAPIView,
    AdminReviewDetailAPIView,
    AdminStockAlertCollectionAPIView,
    AdminStockAlertDetailAPIView,
    AdminVoucherCollectionAPIView,
    AdminVoucherDetailAPIView,
    AdminVoucherOfferCollectionAPIView,
    AdminVoucherStatsAPIView,
    AdminWeightBandCollectionAPIView,
    AdminWeightBandDetailAPIView,
    AdminWeightBasedShippingCollectionAPIView,
    AdminWeightBasedShippingDetailAPIView,
)
from .dashboard_views import AdminCampaignsAPIView, AdminDashboardAPIView, AdminSupportAPIView
from .docs_views import ApiDocsHtmlAPIView, ApiDocsJsonAPIView, ApiRootAPIView
from .email_config_views import (
    AdminEmailConfigurationAPIView,
    AdminEmailLogCollectionAPIView,
    AdminEmailLogDetailAPIView,
    AdminEmailLogRetryAPIView,
    AdminEmailSuppressionCollectionAPIView,
    AdminEmailSuppressionDetailAPIView,
    AdminEmailTemplateCollectionAPIView,
    AdminEmailTemplateDetailAPIView,
    AdminEmailTestAPIView,
)
from .health_views import LivenessAPIView, ReadinessAPIView
from .integration_views import (
    ERPNextCatalogImportAPIView,
    ERPNextConnectionTestAPIView,
    ERPNextPreviewAPIView,
    ERPNextStockSyncAPIView,
    IntegrationConnectionCollectionAPIView,
    IntegrationConnectionDetailAPIView,
    IntegrationLogCollectionAPIView,
)
from .audit_views import AuditLogCollectionAPIView, AuditLogDetailAPIView
from .checkout_views import (
    BasketAPIView,
    BasketItemCollectionAPIView,
    BasketLineDetailAPIView,
    CheckoutPreviewAPIView,
    CheckoutThankYouAPIView,
    OrderPlacementAPIView,
    ShippingAddressAPIView,
    ShippingMethodSelectionAPIView,
    ShippingStateAPIView,
)
from .order_views import (
    AdminOrderCollectionAPIView,
    AdminOrderDetailAPIView,
    AdminOrderStatusAPIView,
    CustomerOrderCollectionAPIView,
    CustomerOrderDetailAPIView,
    CustomerOrderReorderAPIView,
    CustomerOrderStatusAPIView,
)
from .media_views import AdminMediaCollectionAPIView, AdminMediaDetailAPIView
from .marketing_content_views import (
    AdminMarketingBlockCollectionAPIView,
    AdminMarketingBlockDetailAPIView,
    PublicMarketingBlockCollectionAPIView,
)
from .settings_views import AdminSettingsAPIView
from .storefront_views import (
    AccountAddressCollectionAPIView,
    AccountAddressDefaultBillingAPIView,
    AccountAddressDefaultShippingAPIView,
    AccountAddressDetailAPIView,
    AccountDeleteAPIView,
    AccountEmailCollectionAPIView,
    AccountEmailDetailAPIView,
    AccountNotificationArchiveAPIView,
    AccountNotificationCollectionAPIView,
    AccountNotificationDetailAPIView,
    AccountNotificationReadAllAPIView,
    AccountNotificationStateAPIView,
    AccountOrderLineDetailAPIView,
    AccountPreferenceAPIView,
    AccountProductAlertCollectionAPIView,
    AccountProductAlertDetailAPIView,
    BasketLineSaveForLaterAPIView,
    BillingAddressAPIView,
    BillingStateAPIView,
    CatalogRangeDetailAPIView,
    CheckoutAddressCollectionAPIView,
    CheckoutUseBillingAddressAPIView,
    CheckoutUseShippingAddressAPIView,
    GuestOrderDetailAPIView,
    GuestOrderLookupAPIView,
    OfferCollectionAPIView,
    OfferDetailAPIView,
    PasswordResetConfirmAPIView,
    PasswordResetRequestAPIView,
    ProductAlertCancelAPIView,
    ProductAlertConfirmAPIView,
    ProductAlertCreateAPIView,
    ProductReviewDetailAPIView,
    ProductReviewVoteAPIView,
    ProductViewedAPIView,
    RecentlyViewedAPIView,
    SavedItemDetailAPIView,
    SavedItemMoveToCartAPIView,
    SavedItemsAPIView,
    SearchFacetAPIView,
    SharedWishListAPIView,
    StorefrontAnalyticsEventAPIView,
    VoucherApplyAPIView,
    VoucherRemoveAPIView,
    WishListShareAPIView,
    WishListItemMoveAPIView,
)
from .payment_views import (
    AirtelMoneyCallbackAPIView,
    AirtelMoneyInitializationAPIView,
    AirtelMoneyStatusAPIView,
    CardInitializationAPIView,
    MpesaCallbackAPIView,
    MpesaInitializationAPIView,
    MpesaStatusAPIView,
    PaymentConfirmationAPIView,
    PaymentInitializationAPIView,
    PaymentMethodCollectionAPIView,
    PaymentSessionDetailAPIView,
    PesapalInitializationAPIView,
    PesapalNotificationAPIView,
    PesapalStatusAPIView,
)
from .payment_config_views import AdminPaymentConfigurationAPIView, AdminPaymentSessionLogCollectionAPIView
from .review_views import AccountReviewCollectionAPIView, AccountReviewDetailAPIView, ProductReviewCollectionAPIView
from .supplier_views import (
    SupplierAdminCollectionAPIView,
    SupplierAdminDetailAPIView,
    SupplierDashboardAPIView,
    SupplierOrderCollectionAPIView,
    SupplierOrderDetailAPIView,
    SupplierOrderLineStatusAPIView,
    SupplierProductModerationCollectionAPIView,
    SupplierProductModerationDetailAPIView,
    SupplierProductCollectionAPIView,
    SupplierProductDetailAPIView,
    SupplierProductImageCollectionAPIView,
    SupplierProductImageDetailAPIView,
    SupplierProfileAPIView,
)
from .wishlist_views import (
    DefaultWishListAPIView,
    DefaultWishListItemCollectionAPIView,
    DefaultWishListItemDetailAPIView,
    WishListCollectionAPIView,
    WishListDetailAPIView,
    WishListItemCollectionAPIView,
    WishListItemDetailAPIView,
    WishListItemStatusAPIView,
)
from .views import (
    AdminProductCollectionAPIView,
    AdminProductDetailAPIView,
    AdminProductImageCollectionAPIView,
    AdminProductImageDetailAPIView,
    CategoryListAPIView,
    ProductDetailAPIView,
    ProductListAPIView,
    QuoteRequestAPIView,
)
from .user_views import (
    AdminUserCollectionAPIView,
    AdminUserDetailAPIView,
    AdminUserPasswordResetAPIView,
    AdminUserProductAlertCollectionAPIView,
    AdminUserProductAlertDetailAPIView,
)

urlpatterns = [
    path('', ApiRootAPIView.as_view(), name='api-root'),
    path('docs/', ApiDocsHtmlAPIView.as_view(), name='api-docs-html'),
    path('docs.json', ApiDocsJsonAPIView.as_view(), name='api-docs-json'),
    path('health/live/', LivenessAPIView.as_view(), name='health-live'),
    path('health/ready/', ReadinessAPIView.as_view(), name='health-ready'),
    path('account/csrf/', CsrfTokenAPIView.as_view(), name='account-csrf'),
    path('account/register/', AccountRegisterAPIView.as_view(), name='account-register'),
    path('account/login/', AccountLoginAPIView.as_view(), name='account-login'),
    path('account/login/2fa/', AccountLoginTwoFactorAPIView.as_view(), name='account-login-2fa'),
    path('account/reactivation/request/', AccountReactivationRequestAPIView.as_view(), name='account-reactivation-request'),
    path('account/logout/', AccountLogoutAPIView.as_view(), name='account-logout'),
    path('account/email/verify/', AccountEmailVerifyAPIView.as_view(), name='account-email-verify'),
    path('account/email/verification/resend/', AccountEmailVerificationResendAPIView.as_view(), name='account-email-verification-resend'),
    path('account/me/', AccountProfileAPIView.as_view(), name='account-profile'),
    path('account/password/', AccountPasswordAPIView.as_view(), name='account-password'),
    path('account/password-reset/request/', PasswordResetRequestAPIView.as_view(), name='account-password-reset-request'),
    path('account/password-reset/confirm/', PasswordResetConfirmAPIView.as_view(), name='account-password-reset-confirm'),
    path('account/delete/', AccountDeleteAPIView.as_view(), name='account-delete'),
    path('account/preferences/', AccountPreferenceAPIView.as_view(), name='account-preferences'),
    path('account/addresses/', AccountAddressCollectionAPIView.as_view(), name='account-addresses'),
    path('account/addresses/<int:address_id>/', AccountAddressDetailAPIView.as_view(), name='account-address-detail'),
    path('account/addresses/<int:address_id>/default-shipping/', AccountAddressDefaultShippingAPIView.as_view(), name='account-address-default-shipping'),
    path('account/addresses/<int:address_id>/default-billing/', AccountAddressDefaultBillingAPIView.as_view(), name='account-address-default-billing'),
    path('account/emails/', AccountEmailCollectionAPIView.as_view(), name='account-emails'),
    path('account/emails/<int:email_id>/', AccountEmailDetailAPIView.as_view(), name='account-email-detail'),
    path('account/notifications/', AccountNotificationCollectionAPIView.as_view(), name='account-notifications'),
    path('account/notifications/archive/', AccountNotificationArchiveAPIView.as_view(), name='account-notifications-archive'),
    path('account/notifications/<int:notification_id>/', AccountNotificationDetailAPIView.as_view(), name='account-notification-detail'),
    path('account/notifications/<int:notification_id>/read/', AccountNotificationStateAPIView.as_view(), {'action': 'read'}, name='account-notification-read'),
    path('account/notifications/<int:notification_id>/archive/', AccountNotificationStateAPIView.as_view(), {'action': 'archived'}, name='account-notification-archive'),
    path('account/notifications/read-all/', AccountNotificationReadAllAPIView.as_view(), name='account-notifications-read-all'),
    path('account/product-alerts/', AccountProductAlertCollectionAPIView.as_view(), name='account-product-alerts'),
    path('account/product-alerts/<int:alert_id>/', AccountProductAlertDetailAPIView.as_view(), name='account-product-alert-detail'),
    path('account/recently-viewed/', RecentlyViewedAPIView.as_view(), name='account-recently-viewed'),
    path('account/orders/', CustomerOrderCollectionAPIView.as_view(), name='account-orders'),
    path('account/orders/<str:order_number>/', CustomerOrderDetailAPIView.as_view(), name='account-order-detail'),
    path('account/orders/<str:order_number>/lines/<int:line_id>/', AccountOrderLineDetailAPIView.as_view(), name='account-order-line-detail'),
    path('account/orders/<str:order_number>/status/', CustomerOrderStatusAPIView.as_view(), name='account-order-status'),
    path('account/orders/<str:order_number>/reorder/', CustomerOrderReorderAPIView.as_view(), name='account-order-reorder'),
    path('supplier/profile/', SupplierProfileAPIView.as_view(), name='supplier-profile'),
    path('supplier/dashboard/', SupplierDashboardAPIView.as_view(), name='supplier-dashboard'),
    path('supplier/orders/', SupplierOrderCollectionAPIView.as_view(), name='supplier-orders'),
    path('supplier/orders/<str:order_number>/', SupplierOrderDetailAPIView.as_view(), name='supplier-order-detail'),
    path('supplier/orders/<str:order_number>/lines/<int:line_id>/status/', SupplierOrderLineStatusAPIView.as_view(), name='supplier-order-line-status'),
    path('supplier/products/', SupplierProductCollectionAPIView.as_view(), name='supplier-products'),
    path('supplier/products/<int:product_id>/', SupplierProductDetailAPIView.as_view(), name='supplier-product-detail'),
    path('supplier/products/<int:product_id>/images/', SupplierProductImageCollectionAPIView.as_view(), name='supplier-product-images'),
    path('supplier/products/<int:product_id>/images/<int:image_id>/', SupplierProductImageDetailAPIView.as_view(), name='supplier-product-image-detail'),
    path('admin/suppliers/', SupplierAdminCollectionAPIView.as_view(), name='admin-suppliers'),
    path('admin/suppliers/<int:supplier_id>/', SupplierAdminDetailAPIView.as_view(), name='admin-supplier-detail'),
    path('admin/supplier-products/reviews/', SupplierProductModerationCollectionAPIView.as_view(), name='admin-supplier-product-reviews'),
    path('admin/supplier-products/reviews/<int:submission_id>/', SupplierProductModerationDetailAPIView.as_view(), name='admin-supplier-product-review-detail'),
    path('admin/audit-logs/', AuditLogCollectionAPIView.as_view(), name='admin-audit-logs'),
    path('admin/audit-logs/<int:audit_log_id>/', AuditLogDetailAPIView.as_view(), name='admin-audit-log-detail'),
    path('admin/dashboard/', AdminDashboardAPIView.as_view(), name='admin-dashboard'),
    path('admin/dashboard/summary/', AdminDashboardSummaryAPIView.as_view(), name='admin-dashboard-summary'),
    path('admin/campaigns/', AdminCampaignsAPIView.as_view(), name='admin-campaigns'),
    path('admin/support/', AdminSupportAPIView.as_view(), name='admin-support'),
    path('admin/catalog/categories/', AdminCategoryCollectionAPIView.as_view(), name='admin-catalog-categories'),
    path('admin/catalog/categories/<int:category_id>/', AdminCategoryDetailAPIView.as_view(), name='admin-catalog-category-detail'),
    path('admin/catalog/categories/<int:category_id>/children/', AdminCategoryChildrenAPIView.as_view(), name='admin-catalog-category-children'),
    path('admin/catalog/product-types/', AdminProductTypeCollectionAPIView.as_view(), name='admin-catalog-product-types'),
    path('admin/catalog/product-types/<int:product_type_id>/', AdminProductTypeDetailAPIView.as_view(), name='admin-catalog-product-type-detail'),
    path('admin/catalog/attributes/', AdminAttributeCollectionAPIView.as_view(), name='admin-catalog-attributes'),
    path('admin/catalog/attributes/<int:attribute_id>/', AdminAttributeDetailAPIView.as_view(), name='admin-catalog-attribute-detail'),
    path('admin/catalog/options/', AdminOptionCollectionAPIView.as_view(), name='admin-catalog-options'),
    path('admin/catalog/options/<int:option_id>/', AdminOptionDetailAPIView.as_view(), name='admin-catalog-option-detail'),
    path('admin/catalog/stock-alerts/', AdminStockAlertCollectionAPIView.as_view(), name='admin-catalog-stock-alerts'),
    path('admin/catalog/stock-alerts/<int:alert_id>/', AdminStockAlertDetailAPIView.as_view(), name='admin-catalog-stock-alert-detail'),
    path('admin/inventory/low-stock/', AdminLowStockAPIView.as_view(), name='admin-inventory-low-stock'),
    path('admin/vouchers/', AdminVoucherCollectionAPIView.as_view(), name='admin-vouchers'),
    path('admin/vouchers/<int:voucher_id>/', AdminVoucherDetailAPIView.as_view(), name='admin-voucher-detail'),
    path('admin/vouchers/<int:voucher_id>/stats/', AdminVoucherStatsAPIView.as_view(), name='admin-voucher-stats'),
    path('admin/vouchers/<int:voucher_id>/offers/', AdminVoucherOfferCollectionAPIView.as_view(), name='admin-voucher-offers'),
    path('admin/offers/meta/', AdminOfferMetadataAPIView.as_view(), name='admin-offer-meta'),
    path('admin/offers/conditions/', AdminOfferConditionCollectionAPIView.as_view(), name='admin-offer-conditions'),
    path('admin/offers/conditions/<int:condition_id>/', AdminOfferConditionDetailAPIView.as_view(), name='admin-offer-condition-detail'),
    path('admin/offers/benefits/', AdminOfferBenefitCollectionAPIView.as_view(), name='admin-offer-benefits'),
    path('admin/offers/benefits/<int:benefit_id>/', AdminOfferBenefitDetailAPIView.as_view(), name='admin-offer-benefit-detail'),
    path('admin/offers/', AdminOfferCollectionAPIView.as_view(), name='admin-offers'),
    path('admin/offers/<int:offer_id>/', AdminOfferDetailAPIView.as_view(), name='admin-offer-detail'),
    path('admin/offers/<int:offer_id>/status/', AdminOfferStatusAPIView.as_view(), name='admin-offer-status'),
    path('admin/ranges/', AdminRangeCollectionAPIView.as_view(), name='admin-ranges'),
    path('admin/ranges/<int:range_id>/', AdminRangeDetailAPIView.as_view(), name='admin-range-detail'),
    path('admin/ranges/<int:range_id>/products/', AdminRangeProductAPIView.as_view(), name='admin-range-products'),
    path('admin/reviews/', AdminReviewCollectionAPIView.as_view(), name='admin-reviews'),
    path('admin/reviews/<int:review_id>/', AdminReviewDetailAPIView.as_view(), name='admin-review-detail'),
    path('admin/users/', AdminUserCollectionAPIView.as_view(), name='admin-users'),
    path('admin/users/<int:user_id>/', AdminUserDetailAPIView.as_view(), name='admin-user-detail'),
    path('admin/users/<int:user_id>/password-reset/', AdminUserPasswordResetAPIView.as_view(), name='admin-user-password-reset'),
    path('admin/users/<int:user_id>/product-alerts/', AdminUserProductAlertCollectionAPIView.as_view(), name='admin-user-product-alerts'),
    path('admin/users/<int:user_id>/product-alerts/<int:alert_id>/', AdminUserProductAlertDetailAPIView.as_view(), name='admin-user-product-alert-detail'),
    path('admin/media/', AdminMediaCollectionAPIView.as_view(), name='admin-media'),
    path('admin/media/<int:image_id>/', AdminMediaDetailAPIView.as_view(), name='admin-media-detail'),
    path('admin/settings/', AdminSettingsAPIView.as_view(), name='admin-settings'),
    path('admin/email/config/', AdminEmailConfigurationAPIView.as_view(), name='admin-email-config'),
    path('admin/email/test/', AdminEmailTestAPIView.as_view(), name='admin-email-test'),
    path('admin/email/logs/', AdminEmailLogCollectionAPIView.as_view(), name='admin-email-logs'),
    path('admin/email/logs/<int:notification_id>/', AdminEmailLogDetailAPIView.as_view(), name='admin-email-log-detail'),
    path('admin/email/logs/<int:notification_id>/retry/', AdminEmailLogRetryAPIView.as_view(), name='admin-email-log-retry'),
    path('admin/email/suppressions/', AdminEmailSuppressionCollectionAPIView.as_view(), name='admin-email-suppressions'),
    path('admin/email/suppressions/<int:suppression_id>/', AdminEmailSuppressionDetailAPIView.as_view(), name='admin-email-suppression-detail'),
    path('admin/email/templates/', AdminEmailTemplateCollectionAPIView.as_view(), name='admin-email-templates'),
    path('admin/email/templates/<slug:code>/', AdminEmailTemplateDetailAPIView.as_view(), name='admin-email-template-detail'),
    path('admin/payments/config/', AdminPaymentConfigurationAPIView.as_view(), name='admin-payment-config'),
    path('admin/payments/logs/', AdminPaymentSessionLogCollectionAPIView.as_view(), name='admin-payment-logs'),
    path('admin/orders/', AdminOrderCollectionAPIView.as_view(), name='admin-orders'),
    path('admin/orders/statistics/', AdminOrderStatisticsAPIView.as_view(), name='admin-order-statistics'),
    path('admin/orders/<int:order_id>/', AdminOrderDetailAPIView.as_view(), name='admin-order-detail'),
    path('admin/orders/<int:order_id>/status/', AdminOrderStatusAPIView.as_view(), name='admin-order-status'),
    path('admin/orders/<str:order_number>/lines/<int:line_id>/', AdminOrderLineDetailAPIView.as_view(), name='admin-order-line-detail'),
    path('admin/orders/<str:order_number>/shipping-address/', AdminOrderShippingAddressAPIView.as_view(), name='admin-order-shipping-address'),
    path('admin/orders/<str:order_number>/notes/', AdminOrderNoteAPIView.as_view(), name='admin-order-notes'),
    path('admin/partners/', AdminPartnerCollectionAPIView.as_view(), name='admin-partners'),
    path('admin/partners/<int:partner_id>/', AdminPartnerDetailAPIView.as_view(), name='admin-partner-detail'),
    path('admin/partners/<int:partner_id>/users/', AdminPartnerUserCollectionAPIView.as_view(), name='admin-partner-users'),
    path('admin/partners/<int:partner_id>/users/<int:user_id>/link/', AdminPartnerUserLinkAPIView.as_view(), name='admin-partner-user-link'),
    path('admin/partners/<int:partner_id>/users/<int:user_id>/unlink/', AdminPartnerUserLinkAPIView.as_view(), name='admin-partner-user-unlink'),
    path('admin/shipping/weight-based/', AdminWeightBasedShippingCollectionAPIView.as_view(), name='admin-shipping-weight-based'),
    path('admin/shipping/weight-based/<int:method_id>/', AdminWeightBasedShippingDetailAPIView.as_view(), name='admin-shipping-weight-based-detail'),
    path('admin/shipping/weight-based/<int:method_id>/bands/', AdminWeightBandCollectionAPIView.as_view(), name='admin-shipping-weight-bands'),
    path('admin/shipping/weight-based/<int:method_id>/bands/<int:band_id>/', AdminWeightBandDetailAPIView.as_view(), name='admin-shipping-weight-band-detail'),
    path('admin/pages/', AdminPageCollectionAPIView.as_view(), name='admin-pages'),
    path('admin/pages/<int:page_id>/', AdminPageDetailAPIView.as_view(), name='admin-page-detail'),
    path('admin/marketing-blocks/', AdminMarketingBlockCollectionAPIView.as_view(), name='admin-marketing-blocks'),
    path('admin/marketing-blocks/<int:block_id>/', AdminMarketingBlockDetailAPIView.as_view(), name='admin-marketing-block-detail'),
    path('admin/communications/', AdminCommunicationCollectionAPIView.as_view(), name='admin-communications'),
    path('admin/communications/<slug:slug>/', AdminCommunicationDetailAPIView.as_view(), name='admin-communication-detail'),
    path('admin/reports/', AdminReportListAPIView.as_view(), name='admin-reports'),
    path('admin/reports/<slug:report_name>/', AdminReportAPIView.as_view(), name='admin-report-detail'),
    path('admin/integrations/', IntegrationConnectionCollectionAPIView.as_view(), name='admin-integrations'),
    path('admin/integrations/<int:connection_id>/', IntegrationConnectionDetailAPIView.as_view(), name='admin-integration-detail'),
    path('admin/integrations/<int:connection_id>/logs/', IntegrationLogCollectionAPIView.as_view(), name='admin-integration-logs'),
    path('admin/integrations/<int:connection_id>/erpnext/test/', ERPNextConnectionTestAPIView.as_view(), name='admin-integration-erpnext-test'),
    path('admin/integrations/<int:connection_id>/erpnext/preview/', ERPNextPreviewAPIView.as_view(), name='admin-integration-erpnext-preview'),
    path('admin/integrations/<int:connection_id>/erpnext/import/', ERPNextCatalogImportAPIView.as_view(), name='admin-integration-erpnext-import'),
    path('admin/integrations/<int:connection_id>/erpnext/stock-sync/', ERPNextStockSyncAPIView.as_view(), name='admin-integration-erpnext-stock-sync'),
    path('admin/products/', AdminProductCollectionAPIView.as_view(), name='admin-products'),
    path('admin/products/<int:product_id>/', AdminProductDetailAPIView.as_view(), name='admin-product-detail'),
    path('admin/products/<int:product_id>/images/', AdminProductImageCollectionAPIView.as_view(), name='admin-product-images'),
    path('admin/products/<int:product_id>/images/<int:image_id>/', AdminProductImageDetailAPIView.as_view(), name='admin-product-image-detail'),
    path('checkout/basket/', BasketAPIView.as_view(), name='checkout-basket'),
    path('checkout/basket/items/', BasketItemCollectionAPIView.as_view(), name='checkout-basket-items'),
    path('checkout/basket/items/<int:line_id>/', BasketLineDetailAPIView.as_view(), name='checkout-basket-line'),
    path('checkout/basket/items/<int:line_id>/save-for-later/', BasketLineSaveForLaterAPIView.as_view(), name='checkout-basket-line-save-for-later'),
    path('checkout/saved/', SavedItemsAPIView.as_view(), name='checkout-saved-items'),
    path('checkout/saved/items/<int:saved_line_id>/move-to-cart/', SavedItemMoveToCartAPIView.as_view(), name='checkout-saved-item-move-to-cart'),
    path('checkout/saved/items/<int:saved_line_id>/', SavedItemDetailAPIView.as_view(), name='checkout-saved-item-detail'),
    path('checkout/shipping/', ShippingStateAPIView.as_view(), name='checkout-shipping-state'),
    path('checkout/addresses/', CheckoutAddressCollectionAPIView.as_view(), name='checkout-addresses'),
    path('checkout/shipping/address/', ShippingAddressAPIView.as_view(), name='checkout-shipping-address'),
    path('checkout/shipping/use-address/', CheckoutUseShippingAddressAPIView.as_view(), name='checkout-shipping-use-address'),
    path('checkout/shipping/select/', ShippingMethodSelectionAPIView.as_view(), name='checkout-shipping-select'),
    path('checkout/billing/', BillingStateAPIView.as_view(), name='checkout-billing-state'),
    path('checkout/billing/address/', BillingAddressAPIView.as_view(), name='checkout-billing-address'),
    path('checkout/billing/use-address/', CheckoutUseBillingAddressAPIView.as_view(), name='checkout-billing-use-address'),
    path('checkout/preview/', CheckoutPreviewAPIView.as_view(), name='checkout-preview'),
    path('checkout/vouchers/', VoucherApplyAPIView.as_view(), name='checkout-vouchers'),
    path('checkout/vouchers/<int:voucher_id>/', VoucherRemoveAPIView.as_view(), name='checkout-voucher-detail'),
    path('checkout/payments/methods/', PaymentMethodCollectionAPIView.as_view(), name='checkout-payment-methods'),
    path('checkout/payments/', PaymentInitializationAPIView.as_view(), name='checkout-payments'),
    path('checkout/payments/<str:reference>/', PaymentSessionDetailAPIView.as_view(), name='checkout-payment-detail'),
    path('checkout/payments/<str:reference>/confirm/', PaymentConfirmationAPIView.as_view(), name='checkout-payment-confirm'),
    path('checkout/payments/airtel-money/initiate/', AirtelMoneyInitializationAPIView.as_view(), name='checkout-payment-airtel-initiate'),
    path('checkout/payments/airtel-money/<str:reference>/status/', AirtelMoneyStatusAPIView.as_view(), name='checkout-payment-airtel-status'),
    path('checkout/payments/cards/initiate/', CardInitializationAPIView.as_view(), name='checkout-payment-card-initiate'),
    path('checkout/payments/mpesa/initiate/', MpesaInitializationAPIView.as_view(), name='checkout-payment-mpesa-initiate'),
    path('checkout/payments/mpesa/<str:reference>/status/', MpesaStatusAPIView.as_view(), name='checkout-payment-mpesa-status'),
    path('checkout/payments/pesapal/initiate/', PesapalInitializationAPIView.as_view(), name='checkout-payment-pesapal-initiate'),
    path('checkout/payments/pesapal/<str:reference>/status/', PesapalStatusAPIView.as_view(), name='checkout-payment-pesapal-status'),
    path('payments/airtel-money/callback/', AirtelMoneyCallbackAPIView.as_view(), name='payment-airtel-callback'),
    path('payments/mpesa/callback/', MpesaCallbackAPIView.as_view(), name='payment-mpesa-callback'),
    path('payments/pesapal/ipn/', PesapalNotificationAPIView.as_view(), name='payment-pesapal-ipn'),
    path('checkout/orders/', OrderPlacementAPIView.as_view(), name='checkout-orders'),
    path('checkout/thank-you/', CheckoutThankYouAPIView.as_view(), name='checkout-thank-you'),
    path('orders/guest/lookup/', GuestOrderLookupAPIView.as_view(), name='guest-order-lookup'),
    path('orders/guest/<str:order_number>/<path:lookup_hash>/', GuestOrderDetailAPIView.as_view(), name='guest-order-detail'),
    path('account/wishlist/', DefaultWishListAPIView.as_view(), name='account-wishlist-default'),
    path('account/wishlist/items/', DefaultWishListItemCollectionAPIView.as_view(), name='account-wishlist-items-default'),
    path(
        'account/wishlist/items/<int:product_id>/',
        DefaultWishListItemDetailAPIView.as_view(),
        name='account-wishlist-item-default',
    ),
    path('account/wishlist/status/', WishListItemStatusAPIView.as_view(), name='account-wishlist-status'),
    path('account/wishlists/', WishListCollectionAPIView.as_view(), name='account-wishlists'),
    path('account/wishlists/<int:wishlist_id>/', WishListDetailAPIView.as_view(), name='account-wishlist-detail'),
    path('account/wishlists/<int:wishlist_id>/share/', WishListShareAPIView.as_view(), name='account-wishlist-share'),
    path(
        'account/wishlists/<int:wishlist_id>/items/',
        WishListItemCollectionAPIView.as_view(),
        name='account-wishlist-items',
    ),
    path(
        'account/wishlists/<int:wishlist_id>/items/<int:product_id>/',
        WishListItemDetailAPIView.as_view(),
        name='account-wishlist-item',
    ),
    path(
        'account/wishlists/<int:wishlist_id>/items/<int:product_id>/move/',
        WishListItemMoveAPIView.as_view(),
        name='account-wishlist-item-move',
    ),
    path('wishlists/shared/<str:key>/', SharedWishListAPIView.as_view(), name='wishlist-shared'),
    path('account/reviews/', AccountReviewCollectionAPIView.as_view(), name='account-reviews'),
    path('account/reviews/<int:review_id>/', AccountReviewDetailAPIView.as_view(), name='account-review-detail'),
    path('catalog/categories/', CategoryListAPIView.as_view(), name='catalog-categories'),
    path('catalog/ranges/<slug:slug>/', CatalogRangeDetailAPIView.as_view(), name='catalog-range-detail'),
    path('catalog/products/', ProductListAPIView.as_view(), name='catalog-products'),
    path('catalog/products/<int:product_id>/', ProductDetailAPIView.as_view(), name='catalog-product-detail'),
    path('catalog/products/<int:product_id>/reviews/', ProductReviewCollectionAPIView.as_view(), name='catalog-product-reviews'),
    path('catalog/products/<int:product_id>/reviews/<int:review_id>/vote/', ProductReviewVoteAPIView.as_view(), name='catalog-product-review-vote'),
    path('catalog/products/<int:product_id>/reviews/<int:review_id>/', ProductReviewDetailAPIView.as_view(), name='catalog-product-review-detail'),
    path('catalog/products/<int:product_id>/alerts/', ProductAlertCreateAPIView.as_view(), name='catalog-product-alerts'),
    path('catalog/products/<int:product_id>/viewed/', ProductViewedAPIView.as_view(), name='catalog-product-viewed'),
    path('content/marketing-blocks/', PublicMarketingBlockCollectionAPIView.as_view(), name='marketing-blocks'),
    path('product-alerts/confirm/<str:key>/', ProductAlertConfirmAPIView.as_view(), name='product-alert-confirm'),
    path('product-alerts/cancel/<str:key>/', ProductAlertCancelAPIView.as_view(), name='product-alert-cancel'),
    path('offers/', OfferCollectionAPIView.as_view(), name='offers'),
    path('offers/<slug:slug>/', OfferDetailAPIView.as_view(), name='offer-detail'),
    path('quotes/', QuoteRequestAPIView.as_view(), name='quote-request'),
    path('analytics/events/', StorefrontAnalyticsEventAPIView.as_view(), name='storefront-analytics-events'),
    path('search/facets/', SearchFacetAPIView.as_view(), name='search-facets'),
    path('search/', include('apps.search.urls')),
    path('search/image/', include('apps.image_search.urls')),
    path('recommendations/', include('apps.recommendations.urls')),
]
