from django.urls import include, path

from .account_views import (
    AccountLoginAPIView,
    AccountLogoutAPIView,
    AccountPasswordAPIView,
    AccountProfileAPIView,
    AccountRegisterAPIView,
    CsrfTokenAPIView,
)
from .docs_views import ApiDocsHtmlAPIView, ApiDocsJsonAPIView
from .health_views import LivenessAPIView, ReadinessAPIView
from .integration_views import (
    ERPNextCatalogImportAPIView,
    ERPNextConnectionTestAPIView,
    ERPNextPreviewAPIView,
    ERPNextStockSyncAPIView,
    IntegrationConnectionCollectionAPIView,
    IntegrationConnectionDetailAPIView,
    IntegrationLogCollectionAPIView,
)
from .audit_views import AuditLogCollectionAPIView, AuditLogDetailAPIView
from .checkout_views import (
    BasketAPIView,
    BasketItemCollectionAPIView,
    BasketLineDetailAPIView,
    OrderPlacementAPIView,
    ShippingAddressAPIView,
    ShippingMethodSelectionAPIView,
    ShippingStateAPIView,
)
from .order_views import (
    AdminOrderCollectionAPIView,
    AdminOrderDetailAPIView,
    AdminOrderStatusAPIView,
    CustomerOrderCollectionAPIView,
    CustomerOrderDetailAPIView,
    CustomerOrderReorderAPIView,
    CustomerOrderStatusAPIView,
)
from .media_views import AdminMediaCollectionAPIView, AdminMediaDetailAPIView
from .settings_views import AdminSettingsAPIView
from .payment_views import (
    AirtelMoneyCallbackAPIView,
    AirtelMoneyInitializationAPIView,
    AirtelMoneyStatusAPIView,
    CardInitializationAPIView,
    MpesaCallbackAPIView,
    MpesaInitializationAPIView,
    MpesaStatusAPIView,
    PaymentConfirmationAPIView,
    PaymentInitializationAPIView,
    PaymentMethodCollectionAPIView,
    PaymentSessionDetailAPIView,
)
from .review_views import AccountReviewCollectionAPIView, AccountReviewDetailAPIView, ProductReviewCollectionAPIView
from .supplier_views import (
    SupplierAdminCollectionAPIView,
    SupplierAdminDetailAPIView,
    SupplierDashboardAPIView,
    SupplierOrderCollectionAPIView,
    SupplierOrderDetailAPIView,
    SupplierOrderLineStatusAPIView,
    SupplierProductCollectionAPIView,
    SupplierProductDetailAPIView,
    SupplierProfileAPIView,
)
from .wishlist_views import (
    DefaultWishListAPIView,
    DefaultWishListItemCollectionAPIView,
    DefaultWishListItemDetailAPIView,
    WishListCollectionAPIView,
    WishListDetailAPIView,
    WishListItemCollectionAPIView,
    WishListItemDetailAPIView,
    WishListItemStatusAPIView,
)
from .views import (
    AdminProductCollectionAPIView,
    AdminProductDetailAPIView,
    AdminProductImageCollectionAPIView,
    AdminProductImageDetailAPIView,
    CategoryListAPIView,
    ProductDetailAPIView,
    ProductListAPIView,
    QuoteRequestAPIView,
)
from .user_views import AdminUserCollectionAPIView, AdminUserDetailAPIView

urlpatterns = [
    path('docs/', ApiDocsHtmlAPIView.as_view(), name='api-docs-html'),
    path('docs.json', ApiDocsJsonAPIView.as_view(), name='api-docs-json'),
    path('health/live/', LivenessAPIView.as_view(), name='health-live'),
    path('health/ready/', ReadinessAPIView.as_view(), name='health-ready'),
    path('account/csrf/', CsrfTokenAPIView.as_view(), name='account-csrf'),
    path('account/register/', AccountRegisterAPIView.as_view(), name='account-register'),
    path('account/login/', AccountLoginAPIView.as_view(), name='account-login'),
    path('account/logout/', AccountLogoutAPIView.as_view(), name='account-logout'),
    path('account/me/', AccountProfileAPIView.as_view(), name='account-profile'),
    path('account/password/', AccountPasswordAPIView.as_view(), name='account-password'),
    path('account/orders/', CustomerOrderCollectionAPIView.as_view(), name='account-orders'),
    path('account/orders/<str:order_number>/', CustomerOrderDetailAPIView.as_view(), name='account-order-detail'),
    path('account/orders/<str:order_number>/status/', CustomerOrderStatusAPIView.as_view(), name='account-order-status'),
    path('account/orders/<str:order_number>/reorder/', CustomerOrderReorderAPIView.as_view(), name='account-order-reorder'),
    path('supplier/profile/', SupplierProfileAPIView.as_view(), name='supplier-profile'),
    path('supplier/dashboard/', SupplierDashboardAPIView.as_view(), name='supplier-dashboard'),
    path('supplier/orders/', SupplierOrderCollectionAPIView.as_view(), name='supplier-orders'),
    path('supplier/orders/<str:order_number>/', SupplierOrderDetailAPIView.as_view(), name='supplier-order-detail'),
    path('supplier/orders/<str:order_number>/lines/<int:line_id>/status/', SupplierOrderLineStatusAPIView.as_view(), name='supplier-order-line-status'),
    path('supplier/products/', SupplierProductCollectionAPIView.as_view(), name='supplier-products'),
    path('supplier/products/<int:product_id>/', SupplierProductDetailAPIView.as_view(), name='supplier-product-detail'),
    path('admin/suppliers/', SupplierAdminCollectionAPIView.as_view(), name='admin-suppliers'),
    path('admin/suppliers/<int:supplier_id>/', SupplierAdminDetailAPIView.as_view(), name='admin-supplier-detail'),
    path('admin/audit-logs/', AuditLogCollectionAPIView.as_view(), name='admin-audit-logs'),
    path('admin/audit-logs/<int:audit_log_id>/', AuditLogDetailAPIView.as_view(), name='admin-audit-log-detail'),
    path('admin/users/', AdminUserCollectionAPIView.as_view(), name='admin-users'),
    path('admin/users/<int:user_id>/', AdminUserDetailAPIView.as_view(), name='admin-user-detail'),
    path('admin/media/', AdminMediaCollectionAPIView.as_view(), name='admin-media'),
    path('admin/media/<int:image_id>/', AdminMediaDetailAPIView.as_view(), name='admin-media-detail'),
    path('admin/settings/', AdminSettingsAPIView.as_view(), name='admin-settings'),
    path('admin/orders/', AdminOrderCollectionAPIView.as_view(), name='admin-orders'),
    path('admin/orders/<int:order_id>/', AdminOrderDetailAPIView.as_view(), name='admin-order-detail'),
    path('admin/orders/<int:order_id>/status/', AdminOrderStatusAPIView.as_view(), name='admin-order-status'),
    path('admin/integrations/', IntegrationConnectionCollectionAPIView.as_view(), name='admin-integrations'),
    path('admin/integrations/<int:connection_id>/', IntegrationConnectionDetailAPIView.as_view(), name='admin-integration-detail'),
    path('admin/integrations/<int:connection_id>/logs/', IntegrationLogCollectionAPIView.as_view(), name='admin-integration-logs'),
    path('admin/integrations/<int:connection_id>/erpnext/test/', ERPNextConnectionTestAPIView.as_view(), name='admin-integration-erpnext-test'),
    path('admin/integrations/<int:connection_id>/erpnext/preview/', ERPNextPreviewAPIView.as_view(), name='admin-integration-erpnext-preview'),
    path('admin/integrations/<int:connection_id>/erpnext/import/', ERPNextCatalogImportAPIView.as_view(), name='admin-integration-erpnext-import'),
    path('admin/integrations/<int:connection_id>/erpnext/stock-sync/', ERPNextStockSyncAPIView.as_view(), name='admin-integration-erpnext-stock-sync'),
    path('admin/products/', AdminProductCollectionAPIView.as_view(), name='admin-products'),
    path('admin/products/<int:product_id>/', AdminProductDetailAPIView.as_view(), name='admin-product-detail'),
    path('admin/products/<int:product_id>/images/', AdminProductImageCollectionAPIView.as_view(), name='admin-product-images'),
    path('admin/products/<int:product_id>/images/<int:image_id>/', AdminProductImageDetailAPIView.as_view(), name='admin-product-image-detail'),
    path('checkout/basket/', BasketAPIView.as_view(), name='checkout-basket'),
    path('checkout/basket/items/', BasketItemCollectionAPIView.as_view(), name='checkout-basket-items'),
    path('checkout/basket/items/<int:line_id>/', BasketLineDetailAPIView.as_view(), name='checkout-basket-line'),
    path('checkout/shipping/', ShippingStateAPIView.as_view(), name='checkout-shipping-state'),
    path('checkout/shipping/address/', ShippingAddressAPIView.as_view(), name='checkout-shipping-address'),
    path('checkout/shipping/select/', ShippingMethodSelectionAPIView.as_view(), name='checkout-shipping-select'),
    path('checkout/payments/methods/', PaymentMethodCollectionAPIView.as_view(), name='checkout-payment-methods'),
    path('checkout/payments/', PaymentInitializationAPIView.as_view(), name='checkout-payments'),
    path('checkout/payments/<str:reference>/', PaymentSessionDetailAPIView.as_view(), name='checkout-payment-detail'),
    path('checkout/payments/<str:reference>/confirm/', PaymentConfirmationAPIView.as_view(), name='checkout-payment-confirm'),
    path('checkout/payments/airtel-money/initiate/', AirtelMoneyInitializationAPIView.as_view(), name='checkout-payment-airtel-initiate'),
    path('checkout/payments/airtel-money/<str:reference>/status/', AirtelMoneyStatusAPIView.as_view(), name='checkout-payment-airtel-status'),
    path('checkout/payments/cards/initiate/', CardInitializationAPIView.as_view(), name='checkout-payment-card-initiate'),
    path('checkout/payments/mpesa/initiate/', MpesaInitializationAPIView.as_view(), name='checkout-payment-mpesa-initiate'),
    path('checkout/payments/mpesa/<str:reference>/status/', MpesaStatusAPIView.as_view(), name='checkout-payment-mpesa-status'),
    path('payments/airtel-money/callback/', AirtelMoneyCallbackAPIView.as_view(), name='payment-airtel-callback'),
    path('payments/mpesa/callback/', MpesaCallbackAPIView.as_view(), name='payment-mpesa-callback'),
    path('checkout/orders/', OrderPlacementAPIView.as_view(), name='checkout-orders'),
    path('account/wishlist/', DefaultWishListAPIView.as_view(), name='account-wishlist-default'),
    path('account/wishlist/items/', DefaultWishListItemCollectionAPIView.as_view(), name='account-wishlist-items-default'),
    path(
        'account/wishlist/items/<int:product_id>/',
        DefaultWishListItemDetailAPIView.as_view(),
        name='account-wishlist-item-default',
    ),
    path('account/wishlist/status/', WishListItemStatusAPIView.as_view(), name='account-wishlist-status'),
    path('account/wishlists/', WishListCollectionAPIView.as_view(), name='account-wishlists'),
    path('account/wishlists/<int:wishlist_id>/', WishListDetailAPIView.as_view(), name='account-wishlist-detail'),
    path(
        'account/wishlists/<int:wishlist_id>/items/',
        WishListItemCollectionAPIView.as_view(),
        name='account-wishlist-items',
    ),
    path(
        'account/wishlists/<int:wishlist_id>/items/<int:product_id>/',
        WishListItemDetailAPIView.as_view(),
        name='account-wishlist-item',
    ),
    path('account/reviews/', AccountReviewCollectionAPIView.as_view(), name='account-reviews'),
    path('account/reviews/<int:review_id>/', AccountReviewDetailAPIView.as_view(), name='account-review-detail'),
    path('catalog/categories/', CategoryListAPIView.as_view(), name='catalog-categories'),
    path('catalog/products/', ProductListAPIView.as_view(), name='catalog-products'),
    path('catalog/products/<int:product_id>/', ProductDetailAPIView.as_view(), name='catalog-product-detail'),
    path('catalog/products/<int:product_id>/reviews/', ProductReviewCollectionAPIView.as_view(), name='catalog-product-reviews'),
    path('quotes/', QuoteRequestAPIView.as_view(), name='quote-request'),
    path('search/', include('apps.search.urls')),
    path('search/image/', include('apps.image_search.urls')),
    path('recommendations/', include('apps.recommendations.urls')),
]
