export const API_PREFIX = import.meta.env.VITE_API_PREFIX || "/api/v1";

export const ENDPOINTS = {
  docs: {
    html: "/docs/",
    json: "/docs.json"
  },
  health: {
    live: "/health/live/",
    ready: "/health/ready/"
  },
  account: {
    csrf: "/account/csrf/",
    register: "/account/register/",
    login: "/account/login/",
    loginTwoFactor: "/account/login/2fa/",
    logout: "/account/logout/",
    verifyEmail: "/account/email/verify/",
    resendEmailVerification: "/account/email/verification/resend/",
    me: "/account/me/",
    password: "/account/password/",
    passwordResetRequest: "/account/password-reset/request/",
    passwordResetConfirm: "/account/password-reset/confirm/",
    delete: "/account/delete/",
    preferences: "/account/preferences/",
    addresses: "/account/addresses/",
    address: (addressId) => `/account/addresses/${addressId}/`,
    defaultShippingAddress: (addressId) => `/account/addresses/${addressId}/default-shipping/`,
    defaultBillingAddress: (addressId) => `/account/addresses/${addressId}/default-billing/`,
    emails: "/account/emails/",
    email: (emailId) => `/account/emails/${emailId}/`,
    notifications: "/account/notifications/",
    notificationArchive: "/account/notifications/archive/",
    notification: (notificationId) => `/account/notifications/${notificationId}/`,
    notificationRead: (notificationId) => `/account/notifications/${notificationId}/read/`,
    notificationArchiveAction: (notificationId) => `/account/notifications/${notificationId}/archive/`,
    notificationsReadAll: "/account/notifications/read-all/",
    productAlerts: "/account/product-alerts/",
    productAlert: (alertId) => `/account/product-alerts/${alertId}/`,
    recentlyViewed: "/account/recently-viewed/"
  },
  catalog: {
    categories: "/catalog/categories/",
    range: (slug) => `/catalog/ranges/${slug}/`,
    products: "/catalog/products/",
    product: (productId) => `/catalog/products/${productId}/`,
    productReviews: (productId) => `/catalog/products/${productId}/reviews/`,
    productReview: (productId, reviewId) => `/catalog/products/${productId}/reviews/${reviewId}/`,
    productReviewVote: (productId, reviewId) => `/catalog/products/${productId}/reviews/${reviewId}/vote/`,
    productAlerts: (productId) => `/catalog/products/${productId}/alerts/`,
    productViewed: (productId) => `/catalog/products/${productId}/viewed/`
  },
  search: {
    text: "/search/",
    suggestions: "/search/suggestions/",
    facets: "/search/facets/",
    image: "/search/image/"
  },
  offers: {
    list: "/offers/",
    detail: (slug) => `/offers/${slug}/`
  },
  content: {
    marketingBlocks: "/content/marketing-blocks/"
  },
  productAlerts: {
    confirm: (key) => `/product-alerts/confirm/${key}/`,
    cancel: (key) => `/product-alerts/cancel/${key}/`
  },
  recommendations: "/recommendations/",
  quotes: "/quotes/",
  analytics: {
    events: "/analytics/events/"
  },
  wishlist: {
    default: "/account/wishlist/",
    defaultItems: "/account/wishlist/items/",
    defaultItem: (productId) => `/account/wishlist/items/${productId}/`,
    status: "/account/wishlist/status/",
    lists: "/account/wishlists/",
    list: (wishlistId) => `/account/wishlists/${wishlistId}/`,
    share: (wishlistId) => `/account/wishlists/${wishlistId}/share/`,
    listItems: (wishlistId) => `/account/wishlists/${wishlistId}/items/`,
    listItem: (wishlistId, productId) => `/account/wishlists/${wishlistId}/items/${productId}/`,
    moveItem: (wishlistId, productId) => `/account/wishlists/${wishlistId}/items/${productId}/move/`,
    shared: (key) => `/wishlists/shared/${key}/`
  },
  reviews: {
    account: "/account/reviews/",
    accountReview: (reviewId) => `/account/reviews/${reviewId}/`
  },
  checkout: {
    basket: "/checkout/basket/",
    basketItems: "/checkout/basket/items/",
    basketLine: (lineId) => `/checkout/basket/items/${lineId}/`,
    saveForLater: (lineId) => `/checkout/basket/items/${lineId}/save-for-later/`,
    saved: "/checkout/saved/",
    savedItem: (savedLineId) => `/checkout/saved/items/${savedLineId}/`,
    moveSavedToCart: (savedLineId) => `/checkout/saved/items/${savedLineId}/move-to-cart/`,
    shipping: "/checkout/shipping/",
    addresses: "/checkout/addresses/",
    shippingAddress: "/checkout/shipping/address/",
    useShippingAddress: "/checkout/shipping/use-address/",
    shippingSelect: "/checkout/shipping/select/",
    billing: "/checkout/billing/",
    billingAddress: "/checkout/billing/address/",
    useBillingAddress: "/checkout/billing/use-address/",
    preview: "/checkout/preview/",
    vouchers: "/checkout/vouchers/",
    voucher: (voucherId) => `/checkout/vouchers/${voucherId}/`,
    orders: "/checkout/orders/",
    thankYou: "/checkout/thank-you/"
  },
  payments: {
    methods: "/checkout/payments/methods/",
    sessions: "/checkout/payments/",
    session: (reference) => `/checkout/payments/${reference}/`,
    confirm: (reference) => `/checkout/payments/${reference}/confirm/`,
    mpesaInit: "/checkout/payments/mpesa/initiate/",
    mpesaStatus: (reference) => `/checkout/payments/mpesa/${reference}/status/`,
    airtelInit: "/checkout/payments/airtel-money/initiate/",
    airtelStatus: (reference) => `/checkout/payments/airtel-money/${reference}/status/`,
    cardInit: "/checkout/payments/cards/initiate/"
  },
  orders: {
    account: "/account/orders/",
    detail: (orderNumber) => `/account/orders/${orderNumber}/`,
    status: (orderNumber) => `/account/orders/${orderNumber}/status/`,
    reorder: (orderNumber) => `/account/orders/${orderNumber}/reorder/`,
    line: (orderNumber, lineId) => `/account/orders/${orderNumber}/lines/${lineId}/`,
    guestLookup: "/orders/guest/lookup/",
    guestDetail: (orderNumber, hash) => `/orders/guest/${orderNumber}/${hash}/`
  },
  supplier: {
    profile: "/supplier/profile/",
    dashboard: "/supplier/dashboard/",
    orders: "/supplier/orders/",
    order: (orderNumber) => `/supplier/orders/${orderNumber}/`,
    lineStatus: (orderNumber, lineId) => `/supplier/orders/${orderNumber}/lines/${lineId}/status/`,
    products: "/supplier/products/",
    product: (productId) => `/supplier/products/${productId}/`
  },
  admin: {
    dashboardSummary: "/admin/dashboard/summary/",
    catalogCategories: "/admin/catalog/categories/",
    catalogCategory: (categoryId) => `/admin/catalog/categories/${categoryId}/`,
    catalogCategoryChildren: (categoryId) => `/admin/catalog/categories/${categoryId}/children/`,
    productTypes: "/admin/catalog/product-types/",
    productType: (productTypeId) => `/admin/catalog/product-types/${productTypeId}/`,
    attributes: "/admin/catalog/attributes/",
    attribute: (attributeId) => `/admin/catalog/attributes/${attributeId}/`,
    options: "/admin/catalog/options/",
    option: (optionId) => `/admin/catalog/options/${optionId}/`,
    stockAlerts: "/admin/catalog/stock-alerts/",
    stockAlert: (alertId) => `/admin/catalog/stock-alerts/${alertId}/`,
    lowStock: "/admin/inventory/low-stock/",
    vouchers: "/admin/vouchers/",
    voucher: (voucherId) => `/admin/vouchers/${voucherId}/`,
    voucherStats: (voucherId) => `/admin/vouchers/${voucherId}/stats/`,
    offers: "/admin/offers/",
    offer: (offerId) => `/admin/offers/${offerId}/`,
    offerStatus: (offerId) => `/admin/offers/${offerId}/status/`,
    ranges: "/admin/ranges/",
    range: (rangeId) => `/admin/ranges/${rangeId}/`,
    rangeProducts: (rangeId) => `/admin/ranges/${rangeId}/products/`,
    reviews: "/admin/reviews/",
    review: (reviewId) => `/admin/reviews/${reviewId}/`,
    suppliers: "/admin/suppliers/",
    supplier: (supplierId) => `/admin/suppliers/${supplierId}/`,
    auditLogs: "/admin/audit-logs/",
    auditLog: (auditLogId) => `/admin/audit-logs/${auditLogId}/`,
    users: "/admin/users/",
    user: (userId) => `/admin/users/${userId}/`,
    media: "/admin/media/",
    mediaItem: (imageId) => `/admin/media/${imageId}/`,
    settings: "/admin/settings/",
    orders: "/admin/orders/",
    orderStatistics: "/admin/orders/statistics/",
    order: (orderId) => `/admin/orders/${orderId}/`,
    orderStatus: (orderId) => `/admin/orders/${orderId}/status/`,
    orderLine: (orderNumber, lineId) => `/admin/orders/${orderNumber}/lines/${lineId}/`,
    orderShippingAddress: (orderNumber) => `/admin/orders/${orderNumber}/shipping-address/`,
    orderNotes: (orderNumber) => `/admin/orders/${orderNumber}/notes/`,
    partners: "/admin/partners/",
    partner: (partnerId) => `/admin/partners/${partnerId}/`,
    partnerUsers: (partnerId) => `/admin/partners/${partnerId}/users/`,
    partnerUserLink: (partnerId, userId) => `/admin/partners/${partnerId}/users/${userId}/link/`,
    partnerUserUnlink: (partnerId, userId) => `/admin/partners/${partnerId}/users/${userId}/unlink/`,
    weightBasedShipping: "/admin/shipping/weight-based/",
    weightBasedShippingMethod: (methodId) => `/admin/shipping/weight-based/${methodId}/`,
    weightBasedShippingBands: (methodId) => `/admin/shipping/weight-based/${methodId}/bands/`,
    weightBasedShippingBand: (methodId, bandId) => `/admin/shipping/weight-based/${methodId}/bands/${bandId}/`,
    pages: "/admin/pages/",
    page: (pageId) => `/admin/pages/${pageId}/`,
    communications: "/admin/communications/",
    communication: (slug) => `/admin/communications/${slug}/`,
    reports: "/admin/reports/",
    report: (reportName) => `/admin/reports/${reportName}/`,
    integrations: "/admin/integrations/",
    integration: (connectionId) => `/admin/integrations/${connectionId}/`,
    integrationLogs: (connectionId) => `/admin/integrations/${connectionId}/logs/`,
    erpnextTest: (connectionId) => `/admin/integrations/${connectionId}/erpnext/test/`,
    erpnextPreview: (connectionId) => `/admin/integrations/${connectionId}/erpnext/preview/`,
    erpnextImport: (connectionId) => `/admin/integrations/${connectionId}/erpnext/import/`,
    erpnextStockSync: (connectionId) => `/admin/integrations/${connectionId}/erpnext/stock-sync/`,
    products: "/admin/products/",
    product: (productId) => `/admin/products/${productId}/`,
    productImages: (productId) => `/admin/products/${productId}/images/`,
    productImage: (productId, imageId) => `/admin/products/${productId}/images/${imageId}/`
  }
};
