# Generated by Django 4.2.29 on 2026-06-11 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_pesapal_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initialized', 'Initialized'), ('provider_submitted', 'Provider submitted'), ('notification_received', 'Notification received'), ('status_queried', 'Status queried'), ('status_applied', 'Status applied'), ('status_ignored', 'Status ignored'), ('gateway_error', 'Gateway error'), ('order_linked', 'Order linked')], max_length=40)),
                ('status_before', models.CharField(blank=True, max_length=16)),
                ('status_after', models.CharField(blank=True, max_length=16)),
                ('external_reference', models.CharField(blank=True, max_length=128)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.paymentsession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['kind', '-created_at'], name='payments_pa_kind_71b3e6_idx'), models.Index(fields=['payment_session', '-created_at'], name='payments_pa_payment_7d76e5_idx')],
            },
        ),
    ]
