# Generated by Codex on 2026-07-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0018_alter_line_num_allocated'),
        ('payments', '0004_paymentevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=32)),
                ('merchant_reference', models.CharField(max_length=64)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('amount_mismatch', 'Amount Mismatch'), ('duplicate', 'Duplicate'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed'), ('refunded', 'Refunded'), ('manual_review', 'Manual Review')], default='pending', max_length=32)),
                ('issues', models.JSONField(blank=True, default=list)),
                ('raw_provider_payload', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.TextField(blank=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reconciliations', to='order.order')),
                ('payment_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='payments.paymentsession')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [
                    models.Index(fields=['status', '-updated_at'], name='payments_pa_status_fb79a4_idx'),
                    models.Index(fields=['provider', 'provider_reference'], name='payments_pa_provide_809294_idx'),
                    models.Index(fields=['merchant_reference'], name='payments_pa_merchan_18873a_idx'),
                    models.Index(fields=['order', 'status'], name='payments_pa_order_i_9e7efb_idx'),
                ],
            },
        ),
    ]
