# Generated by Django 4.2.29 on 2026-07-28 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_line_num_allocated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_paymentreconciliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefundLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_type', models.CharField(choices=[('refund', 'Refund'), ('cancellation', 'Cancellation'), ('return', 'Return'), ('adjustment', 'Adjustment')], default='refund', max_length=32)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('refund_reference', models.CharField(max_length=128, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=128)),
                ('gateway', models.CharField(blank=True, max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('gateway_payload', models.JSONField(blank=True, default=dict)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_ledgers', to='order.line')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_ledgers', to='order.order')),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_ledgers', to='payments.paymentsession')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_ledgers', to='payments.paymentreconciliation')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_refunds', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_b31e73_idx'), models.Index(fields=['refund_type', 'status'], name='payments_pa_refund__71882b_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_dcd4f7_idx'), models.Index(fields=['payment_session', 'status'], name='payments_pa_payment_a9a2bd_idx'), models.Index(fields=['refund_reference'], name='payments_pa_refund__78f07d_idx')],
            },
        ),
    ]
