# Generated by Django 4.2.29 on 2026-07-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_paymentrefundledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreconciliation',
            name='erpnext_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='erpnext_sync_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentreconciliation',
            name='erpnext_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='completion_state',
            field=models.CharField(choices=[('partial_requested', 'Partial Requested'), ('full_requested', 'Full Requested'), ('partial_submitted', 'Partial Submitted'), ('full_submitted', 'Full Submitted'), ('partial_completed', 'Partial Completed'), ('full_completed', 'Full Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='partial_requested', max_length=32),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='erpnext_reference',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='erpnext_sync_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='erpnext_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='erpnext_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentrefundledger',
            name='refund_scope',
            field=models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], default='partial', max_length=16),
        ),
        migrations.AddIndex(
            model_name='paymentrefundledger',
            index=models.Index(fields=['refund_scope', 'completion_state'], name='payments_pa_refund__1a07ad_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefundledger',
            index=models.Index(fields=['erpnext_sync_status', '-created_at'], name='payments_pa_erpnext_5a3294_idx'),
        ),
    ]
