# Generated by Django 4.2.29 on 2026-07-29 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_auto_20200724_0909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogue', '0027_attributeoption_code_attributeoptiongroup_code_and_more'),
        ('order', '0018_alter_line_num_allocated'),
        ('payments', '0007_paymentreconciliation_erpnext_reference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReturnCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_reference', models.CharField(max_length=128, unique=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('accepted_quantity', models.PositiveIntegerField(default=0)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='KES', max_length=12)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('received', 'Received'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('restock_decision', models.CharField(choices=[('pending', 'Pending'), ('restock', 'Restock'), ('quarantine', 'Quarantine'), ('scrap', 'Scrap'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('condition_note', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('erpnext_rule', models.CharField(default='credit_note', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('restocked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_cases', to='order.line')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_cases', to='order.order')),
                ('payment_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_cases', to='payments.paymentsession')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases', to='catalogue.product')),
                ('reconciliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases', to='payments.paymentreconciliation')),
                ('refund_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases', to='payments.paymentrefundledger')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payment_returns', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_returns', to=settings.AUTH_USER_MODEL)),
                ('stockrecord', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_cases', to='partner.stockrecord')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='payments_pa_status_535bd0_idx'), models.Index(fields=['order', 'status'], name='payments_pa_order_i_c40220_idx'), models.Index(fields=['line', 'status'], name='payments_pa_line_id_200a90_idx'), models.Index(fields=['return_reference'], name='payments_pa_return__b39c71_idx')],
            },
        ),
    ]
