# Generated by Django 4.2.29 on 2026-07-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_paymentreturncase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproviderconfiguration',
            name='provider',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('pesapal', 'Pesapal'), ('airtel_money', 'Airtel Money'), ('card', 'Card'), ('cash_on_delivery', 'Cash on Delivery')], max_length=32, unique=True),
        ),
    ]
